/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { SurveyDetailResponse } from ".././models";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 비회원이 PUBLIC 설문의 양식(질문·선택지·행)을 조회합니다. PUBLIC + PUBLISHED + OPEN 상태에서만 조회 가능합니다. 인증 불필요.
 * @summary 설문 양식 조회 (비회원용)
 */
export type getAnonymousSurveyFormResponse200 = {
  data: SurveyDetailResponse;
  status: 200;
};

export type getAnonymousSurveyFormResponse400 = {
  data: void;
  status: 400;
};

export type getAnonymousSurveyFormResponse403 = {
  data: void;
  status: 403;
};

export type getAnonymousSurveyFormResponse404 = {
  data: void;
  status: 404;
};

export type getAnonymousSurveyFormResponseSuccess =
  getAnonymousSurveyFormResponse200 & {
    headers: Headers;
  };
export type getAnonymousSurveyFormResponseError = (
  | getAnonymousSurveyFormResponse400
  | getAnonymousSurveyFormResponse403
  | getAnonymousSurveyFormResponse404
) & {
  headers: Headers;
};

export type getAnonymousSurveyFormResponse =
  | getAnonymousSurveyFormResponseSuccess
  | getAnonymousSurveyFormResponseError;

export const getGetAnonymousSurveyFormUrl = (surveyId: number) => {
  return `/api/v1/surveys/${surveyId}/form/anonymous`;
};

export const getAnonymousSurveyForm = async (
  surveyId: number,
  options?: RequestInit,
): Promise<getAnonymousSurveyFormResponse> => {
  return customFetch<getAnonymousSurveyFormResponse>(
    getGetAnonymousSurveyFormUrl(surveyId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAnonymousSurveyFormQueryKey = (surveyId: number) => {
  return [`/api/v1/surveys/${surveyId}/form/anonymous`] as const;
};

export const getGetAnonymousSurveyFormQueryOptions = <
  TData = Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAnonymousSurveyFormQueryKey(surveyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAnonymousSurveyForm>>
  > = ({ signal }) =>
    getAnonymousSurveyForm(surveyId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!surveyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAnonymousSurveyFormQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAnonymousSurveyForm>>
>;
export type GetAnonymousSurveyFormQueryError = void;

export function useGetAnonymousSurveyForm<
  TData = Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
  TError = void,
>(
  surveyId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
          TError,
          Awaited<ReturnType<typeof getAnonymousSurveyForm>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAnonymousSurveyForm<
  TData = Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
          TError,
          Awaited<ReturnType<typeof getAnonymousSurveyForm>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAnonymousSurveyForm<
  TData = Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 설문 양식 조회 (비회원용)
 */

export function useGetAnonymousSurveyForm<
  TData = Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnonymousSurveyForm>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAnonymousSurveyFormQueryOptions(surveyId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
