/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckConsentedToVersionParams,
  CheckNeedsReConsentParams,
  ConsentCheckResponse,
  PrivacyConsentHistoryResponse,
  PrivacyConsentResponse
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 사용자가 현재 정책 버전에 재동의가 필요한지 확인합니다
 * @summary 재동의 필요 여부 확인
 */
export type checkNeedsReConsentResponse200 = {
  data: ConsentCheckResponse
  status: 200
}

export type checkNeedsReConsentResponse401 = {
  data: ConsentCheckResponse
  status: 401
}
    
export type checkNeedsReConsentResponseSuccess = (checkNeedsReConsentResponse200) & {
  headers: Headers;
};
export type checkNeedsReConsentResponseError = (checkNeedsReConsentResponse401) & {
  headers: Headers;
};

export type checkNeedsReConsentResponse = (checkNeedsReConsentResponseSuccess | checkNeedsReConsentResponseError)

export const getCheckNeedsReConsentUrl = (params: CheckNeedsReConsentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/privacy/consent/needs-reconsent?${stringifiedParams}` : `/api/v1/privacy/consent/needs-reconsent`
}

export const checkNeedsReConsent = async (params: CheckNeedsReConsentParams, options?: RequestInit): Promise<checkNeedsReConsentResponse> => {
  
  return customFetch<checkNeedsReConsentResponse>(getCheckNeedsReConsentUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCheckNeedsReConsentQueryKey = (params?: CheckNeedsReConsentParams,) => {
    return [
    `/api/v1/privacy/consent/needs-reconsent`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCheckNeedsReConsentQueryOptions = <TData = Awaited<ReturnType<typeof checkNeedsReConsent>>, TError = ConsentCheckResponse>(params: CheckNeedsReConsentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNeedsReConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckNeedsReConsentQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkNeedsReConsent>>> = ({ signal }) => checkNeedsReConsent(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkNeedsReConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckNeedsReConsentQueryResult = NonNullable<Awaited<ReturnType<typeof checkNeedsReConsent>>>
export type CheckNeedsReConsentQueryError = ConsentCheckResponse


export function useCheckNeedsReConsent<TData = Awaited<ReturnType<typeof checkNeedsReConsent>>, TError = ConsentCheckResponse>(
 params: CheckNeedsReConsentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNeedsReConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkNeedsReConsent>>,
          TError,
          Awaited<ReturnType<typeof checkNeedsReConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckNeedsReConsent<TData = Awaited<ReturnType<typeof checkNeedsReConsent>>, TError = ConsentCheckResponse>(
 params: CheckNeedsReConsentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNeedsReConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkNeedsReConsent>>,
          TError,
          Awaited<ReturnType<typeof checkNeedsReConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckNeedsReConsent<TData = Awaited<ReturnType<typeof checkNeedsReConsent>>, TError = ConsentCheckResponse>(
 params: CheckNeedsReConsentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNeedsReConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 재동의 필요 여부 확인
 */

export function useCheckNeedsReConsent<TData = Awaited<ReturnType<typeof checkNeedsReConsent>>, TError = ConsentCheckResponse>(
 params: CheckNeedsReConsentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNeedsReConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckNeedsReConsentQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 사용자의 최신 개인정보 동의 기록을 조회합니다
 * @summary 최신 동의 기록 조회
 */
export type getLatestConsentResponse200 = {
  data: PrivacyConsentResponse
  status: 200
}

export type getLatestConsentResponse401 = {
  data: PrivacyConsentResponse
  status: 401
}

export type getLatestConsentResponse404 = {
  data: PrivacyConsentResponse
  status: 404
}
    
export type getLatestConsentResponseSuccess = (getLatestConsentResponse200) & {
  headers: Headers;
};
export type getLatestConsentResponseError = (getLatestConsentResponse401 | getLatestConsentResponse404) & {
  headers: Headers;
};

export type getLatestConsentResponse = (getLatestConsentResponseSuccess | getLatestConsentResponseError)

export const getGetLatestConsentUrl = () => {


  

  return `/api/v1/privacy/consent/latest`
}

export const getLatestConsent = async ( options?: RequestInit): Promise<getLatestConsentResponse> => {
  
  return customFetch<getLatestConsentResponse>(getGetLatestConsentUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetLatestConsentQueryKey = () => {
    return [
    `/api/v1/privacy/consent/latest`
    ] as const;
    }

    
export const getGetLatestConsentQueryOptions = <TData = Awaited<ReturnType<typeof getLatestConsent>>, TError = PrivacyConsentResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLatestConsentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLatestConsent>>> = ({ signal }) => getLatestConsent({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLatestConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLatestConsentQueryResult = NonNullable<Awaited<ReturnType<typeof getLatestConsent>>>
export type GetLatestConsentQueryError = PrivacyConsentResponse


export function useGetLatestConsent<TData = Awaited<ReturnType<typeof getLatestConsent>>, TError = PrivacyConsentResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestConsent>>,
          TError,
          Awaited<ReturnType<typeof getLatestConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLatestConsent<TData = Awaited<ReturnType<typeof getLatestConsent>>, TError = PrivacyConsentResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestConsent>>,
          TError,
          Awaited<ReturnType<typeof getLatestConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLatestConsent<TData = Awaited<ReturnType<typeof getLatestConsent>>, TError = PrivacyConsentResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 최신 동의 기록 조회
 */

export function useGetLatestConsent<TData = Awaited<ReturnType<typeof getLatestConsent>>, TError = PrivacyConsentResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLatestConsentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 사용자의 개인정보 동의 이력을 조회합니다
 * @summary 동의 이력 조회
 */
export type getConsentHistoryResponse200 = {
  data: PrivacyConsentHistoryResponse
  status: 200
}

export type getConsentHistoryResponse401 = {
  data: PrivacyConsentHistoryResponse
  status: 401
}
    
export type getConsentHistoryResponseSuccess = (getConsentHistoryResponse200) & {
  headers: Headers;
};
export type getConsentHistoryResponseError = (getConsentHistoryResponse401) & {
  headers: Headers;
};

export type getConsentHistoryResponse = (getConsentHistoryResponseSuccess | getConsentHistoryResponseError)

export const getGetConsentHistoryUrl = () => {


  

  return `/api/v1/privacy/consent/history`
}

export const getConsentHistory = async ( options?: RequestInit): Promise<getConsentHistoryResponse> => {
  
  return customFetch<getConsentHistoryResponse>(getGetConsentHistoryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetConsentHistoryQueryKey = () => {
    return [
    `/api/v1/privacy/consent/history`
    ] as const;
    }

    
export const getGetConsentHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getConsentHistory>>, TError = PrivacyConsentHistoryResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsentHistory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConsentHistoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConsentHistory>>> = ({ signal }) => getConsentHistory({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConsentHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConsentHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentHistory>>>
export type GetConsentHistoryQueryError = PrivacyConsentHistoryResponse


export function useGetConsentHistory<TData = Awaited<ReturnType<typeof getConsentHistory>>, TError = PrivacyConsentHistoryResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsentHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConsentHistory>>,
          TError,
          Awaited<ReturnType<typeof getConsentHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConsentHistory<TData = Awaited<ReturnType<typeof getConsentHistory>>, TError = PrivacyConsentHistoryResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsentHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConsentHistory>>,
          TError,
          Awaited<ReturnType<typeof getConsentHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConsentHistory<TData = Awaited<ReturnType<typeof getConsentHistory>>, TError = PrivacyConsentHistoryResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsentHistory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 동의 이력 조회
 */

export function useGetConsentHistory<TData = Awaited<ReturnType<typeof getConsentHistory>>, TError = PrivacyConsentHistoryResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsentHistory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConsentHistoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 사용자가 동의한 기록이 있는지 확인합니다
 * @summary 동의 기록 존재 확인
 */
export type checkHasConsentResponse200 = {
  data: ConsentCheckResponse
  status: 200
}

export type checkHasConsentResponse401 = {
  data: ConsentCheckResponse
  status: 401
}
    
export type checkHasConsentResponseSuccess = (checkHasConsentResponse200) & {
  headers: Headers;
};
export type checkHasConsentResponseError = (checkHasConsentResponse401) & {
  headers: Headers;
};

export type checkHasConsentResponse = (checkHasConsentResponseSuccess | checkHasConsentResponseError)

export const getCheckHasConsentUrl = () => {


  

  return `/api/v1/privacy/consent/check`
}

export const checkHasConsent = async ( options?: RequestInit): Promise<checkHasConsentResponse> => {
  
  return customFetch<checkHasConsentResponse>(getCheckHasConsentUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCheckHasConsentQueryKey = () => {
    return [
    `/api/v1/privacy/consent/check`
    ] as const;
    }

    
export const getCheckHasConsentQueryOptions = <TData = Awaited<ReturnType<typeof checkHasConsent>>, TError = ConsentCheckResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkHasConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckHasConsentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkHasConsent>>> = ({ signal }) => checkHasConsent({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkHasConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckHasConsentQueryResult = NonNullable<Awaited<ReturnType<typeof checkHasConsent>>>
export type CheckHasConsentQueryError = ConsentCheckResponse


export function useCheckHasConsent<TData = Awaited<ReturnType<typeof checkHasConsent>>, TError = ConsentCheckResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkHasConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkHasConsent>>,
          TError,
          Awaited<ReturnType<typeof checkHasConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckHasConsent<TData = Awaited<ReturnType<typeof checkHasConsent>>, TError = ConsentCheckResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkHasConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkHasConsent>>,
          TError,
          Awaited<ReturnType<typeof checkHasConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckHasConsent<TData = Awaited<ReturnType<typeof checkHasConsent>>, TError = ConsentCheckResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkHasConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 동의 기록 존재 확인
 */

export function useCheckHasConsent<TData = Awaited<ReturnType<typeof checkHasConsent>>, TError = ConsentCheckResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkHasConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckHasConsentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 사용자가 특정 버전의 정책에 동의했는지 확인합니다
 * @summary 특정 버전 동의 확인
 */
export type checkConsentedToVersionResponse200 = {
  data: ConsentCheckResponse
  status: 200
}

export type checkConsentedToVersionResponse401 = {
  data: ConsentCheckResponse
  status: 401
}
    
export type checkConsentedToVersionResponseSuccess = (checkConsentedToVersionResponse200) & {
  headers: Headers;
};
export type checkConsentedToVersionResponseError = (checkConsentedToVersionResponse401) & {
  headers: Headers;
};

export type checkConsentedToVersionResponse = (checkConsentedToVersionResponseSuccess | checkConsentedToVersionResponseError)

export const getCheckConsentedToVersionUrl = (params: CheckConsentedToVersionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/privacy/consent/check-version?${stringifiedParams}` : `/api/v1/privacy/consent/check-version`
}

export const checkConsentedToVersion = async (params: CheckConsentedToVersionParams, options?: RequestInit): Promise<checkConsentedToVersionResponse> => {
  
  return customFetch<checkConsentedToVersionResponse>(getCheckConsentedToVersionUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCheckConsentedToVersionQueryKey = (params?: CheckConsentedToVersionParams,) => {
    return [
    `/api/v1/privacy/consent/check-version`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCheckConsentedToVersionQueryOptions = <TData = Awaited<ReturnType<typeof checkConsentedToVersion>>, TError = ConsentCheckResponse>(params: CheckConsentedToVersionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkConsentedToVersion>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckConsentedToVersionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkConsentedToVersion>>> = ({ signal }) => checkConsentedToVersion(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkConsentedToVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckConsentedToVersionQueryResult = NonNullable<Awaited<ReturnType<typeof checkConsentedToVersion>>>
export type CheckConsentedToVersionQueryError = ConsentCheckResponse


export function useCheckConsentedToVersion<TData = Awaited<ReturnType<typeof checkConsentedToVersion>>, TError = ConsentCheckResponse>(
 params: CheckConsentedToVersionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkConsentedToVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkConsentedToVersion>>,
          TError,
          Awaited<ReturnType<typeof checkConsentedToVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckConsentedToVersion<TData = Awaited<ReturnType<typeof checkConsentedToVersion>>, TError = ConsentCheckResponse>(
 params: CheckConsentedToVersionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkConsentedToVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkConsentedToVersion>>,
          TError,
          Awaited<ReturnType<typeof checkConsentedToVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckConsentedToVersion<TData = Awaited<ReturnType<typeof checkConsentedToVersion>>, TError = ConsentCheckResponse>(
 params: CheckConsentedToVersionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkConsentedToVersion>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 특정 버전 동의 확인
 */

export function useCheckConsentedToVersion<TData = Awaited<ReturnType<typeof checkConsentedToVersion>>, TError = ConsentCheckResponse>(
 params: CheckConsentedToVersionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkConsentedToVersion>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckConsentedToVersionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




