/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 댓글에 좋아요를 추가합니다. 본인 댓글에는 좋아요할 수 없습니다.
 * @summary 댓글 좋아요
 */
export type likeCommentResponse201 = {
  data: void;
  status: 201;
};

export type likeCommentResponse400 = {
  data: void;
  status: 400;
};

export type likeCommentResponse401 = {
  data: void;
  status: 401;
};

export type likeCommentResponse404 = {
  data: void;
  status: 404;
};

export type likeCommentResponseSuccess = likeCommentResponse201 & {
  headers: Headers;
};
export type likeCommentResponseError = (
  | likeCommentResponse400
  | likeCommentResponse401
  | likeCommentResponse404
) & {
  headers: Headers;
};

export type likeCommentResponse =
  | likeCommentResponseSuccess
  | likeCommentResponseError;

export const getLikeCommentUrl = (commentId: number) => {
  return `/api/v1/comments/${commentId}/likes`;
};

export const likeComment = async (
  commentId: number,
  options?: RequestInit,
): Promise<likeCommentResponse> => {
  return customFetch<likeCommentResponse>(getLikeCommentUrl(commentId), {
    ...options,
    method: "POST",
  });
};

export const getLikeCommentMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ["likeComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return likeComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeComment>>
>;

export type LikeCommentMutationError = void;

/**
 * @summary 댓글 좋아요
 */
export const useLikeComment = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof likeComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof likeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  return useMutation(getLikeCommentMutationOptions(options), queryClient);
};
/**
 * 댓글 좋아요를 취소합니다.
 * @summary 댓글 좋아요 취소
 */
export type unlikeCommentResponse204 = {
  data: void;
  status: 204;
};

export type unlikeCommentResponse401 = {
  data: void;
  status: 401;
};

export type unlikeCommentResponse404 = {
  data: void;
  status: 404;
};

export type unlikeCommentResponseSuccess = unlikeCommentResponse204 & {
  headers: Headers;
};
export type unlikeCommentResponseError = (
  | unlikeCommentResponse401
  | unlikeCommentResponse404
) & {
  headers: Headers;
};

export type unlikeCommentResponse =
  | unlikeCommentResponseSuccess
  | unlikeCommentResponseError;

export const getUnlikeCommentUrl = (commentId: number) => {
  return `/api/v1/comments/${commentId}/likes`;
};

export const unlikeComment = async (
  commentId: number,
  options?: RequestInit,
): Promise<unlikeCommentResponse> => {
  return customFetch<unlikeCommentResponse>(getUnlikeCommentUrl(commentId), {
    ...options,
    method: "DELETE",
  });
};

export const getUnlikeCommentMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unlikeComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unlikeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ["unlikeComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unlikeComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return unlikeComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnlikeCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof unlikeComment>>
>;

export type UnlikeCommentMutationError = void;

/**
 * @summary 댓글 좋아요 취소
 */
export const useUnlikeComment = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unlikeComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unlikeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  return useMutation(getUnlikeCommentMutationOptions(options), queryClient);
};
