/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: 33c8ee9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateEventRequest,
  EventCreateResponse,
  EventDetailResponse,
  EventListResponse,
  GetEventListParams,
  UpdateEventRequest
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 행사의 상세 정보를 조회합니다. 준회원은 조회할 수 없습니다.
 * @summary 행사 상세 조회
 */
export type getEventResponse200 = {
  data: EventDetailResponse
  status: 200
}

export type getEventResponse401 = {
  data: EventDetailResponse
  status: 401
}

export type getEventResponse403 = {
  data: EventDetailResponse
  status: 403
}

export type getEventResponse404 = {
  data: EventDetailResponse
  status: 404
}
    
export type getEventResponseSuccess = (getEventResponse200) & {
  headers: Headers;
};
export type getEventResponseError = (getEventResponse401 | getEventResponse403 | getEventResponse404) & {
  headers: Headers;
};

export type getEventResponse = (getEventResponseSuccess | getEventResponseError)

export const getGetEventUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}`
}

export const getEvent = async (eventId: number, options?: RequestInit): Promise<getEventResponse> => {
  
  return customFetch<getEventResponse>(getGetEventUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEventQueryKey = (eventId: number,) => {
    return [
    `/api/v1/events/${eventId}`
    ] as const;
    }

    
export const getGetEventQueryOptions = <TData = Awaited<ReturnType<typeof getEvent>>, TError = EventDetailResponse>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvent>>> = ({ signal }) => getEvent(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventQueryResult = NonNullable<Awaited<ReturnType<typeof getEvent>>>
export type GetEventQueryError = EventDetailResponse


export function useGetEvent<TData = Awaited<ReturnType<typeof getEvent>>, TError = EventDetailResponse>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvent>>,
          TError,
          Awaited<ReturnType<typeof getEvent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvent<TData = Awaited<ReturnType<typeof getEvent>>, TError = EventDetailResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvent>>,
          TError,
          Awaited<ReturnType<typeof getEvent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvent<TData = Awaited<ReturnType<typeof getEvent>>, TError = EventDetailResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 행사 상세 조회
 */

export function useGetEvent<TData = Awaited<ReturnType<typeof getEvent>>, TError = EventDetailResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 행사 정보를 수정합니다. 작성자 또는 관리자만 가능합니다.
 * @summary 행사 수정
 */
export type updateEventResponse200 = {
  data: EventDetailResponse
  status: 200
}

export type updateEventResponse400 = {
  data: EventDetailResponse
  status: 400
}

export type updateEventResponse401 = {
  data: EventDetailResponse
  status: 401
}

export type updateEventResponse403 = {
  data: EventDetailResponse
  status: 403
}

export type updateEventResponse404 = {
  data: EventDetailResponse
  status: 404
}
    
export type updateEventResponseSuccess = (updateEventResponse200) & {
  headers: Headers;
};
export type updateEventResponseError = (updateEventResponse400 | updateEventResponse401 | updateEventResponse403 | updateEventResponse404) & {
  headers: Headers;
};

export type updateEventResponse = (updateEventResponseSuccess | updateEventResponseError)

export const getUpdateEventUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}`
}

export const updateEvent = async (eventId: number,
    updateEventRequest: UpdateEventRequest, options?: RequestInit): Promise<updateEventResponse> => {
  
  return customFetch<updateEventResponse>(getUpdateEventUrl(eventId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventRequest,)
  }
);}




export const getUpdateEventMutationOptions = <TError = EventDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{eventId: number;data: UpdateEventRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{eventId: number;data: UpdateEventRequest}, TContext> => {

const mutationKey = ['updateEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEvent>>, {eventId: number;data: UpdateEventRequest}> = (props) => {
          const {eventId,data} = props ?? {};

          return  updateEvent(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEventMutationResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>
    export type UpdateEventMutationBody = UpdateEventRequest
    export type UpdateEventMutationError = EventDetailResponse

    /**
 * @summary 행사 수정
 */
export const useUpdateEvent = <TError = EventDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{eventId: number;data: UpdateEventRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEvent>>,
        TError,
        {eventId: number;data: UpdateEventRequest},
        TContext
      > => {
      return useMutation(getUpdateEventMutationOptions(options), queryClient);
    }
    /**
 * 행사를 삭제합니다. 작성자 또는 관리자만 가능합니다.
 * @summary 행사 삭제
 */
export type deleteEventResponse204 = {
  data: void
  status: 204
}

export type deleteEventResponse401 = {
  data: void
  status: 401
}

export type deleteEventResponse403 = {
  data: void
  status: 403
}

export type deleteEventResponse404 = {
  data: void
  status: 404
}
    
export type deleteEventResponseSuccess = (deleteEventResponse204) & {
  headers: Headers;
};
export type deleteEventResponseError = (deleteEventResponse401 | deleteEventResponse403 | deleteEventResponse404) & {
  headers: Headers;
};

export type deleteEventResponse = (deleteEventResponseSuccess | deleteEventResponseError)

export const getDeleteEventUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}`
}

export const deleteEvent = async (eventId: number, options?: RequestInit): Promise<deleteEventResponse> => {
  
  return customFetch<deleteEventResponse>(getDeleteEventUrl(eventId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteEventMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['deleteEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEvent>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  deleteEvent(eventId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>
    
    export type DeleteEventMutationError = void

    /**
 * @summary 행사 삭제
 */
export const useDeleteEvent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEvent>>,
        TError,
        {eventId: number},
        TContext
      > => {
      return useMutation(getDeleteEventMutationOptions(options), queryClient);
    }
    /**
 * 행사 목록을 조회합니다. 상태별 필터링이 가능합니다.
 * @summary 행사 목록 조회
 */
export type getEventListResponse200 = {
  data: EventListResponse[]
  status: 200
}

export type getEventListResponse401 = {
  data: EventListResponse[]
  status: 401
}
    
export type getEventListResponseSuccess = (getEventListResponse200) & {
  headers: Headers;
};
export type getEventListResponseError = (getEventListResponse401) & {
  headers: Headers;
};

export type getEventListResponse = (getEventListResponseSuccess | getEventListResponseError)

export const getGetEventListUrl = (params?: GetEventListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/events?${stringifiedParams}` : `/api/v1/events`
}

export const getEventList = async (params?: GetEventListParams, options?: RequestInit): Promise<getEventListResponse> => {
  
  return customFetch<getEventListResponse>(getGetEventListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEventListQueryKey = (params?: GetEventListParams,) => {
    return [
    `/api/v1/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetEventListQueryOptions = <TData = Awaited<ReturnType<typeof getEventList>>, TError = EventListResponse[]>(params?: GetEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventList>>> = ({ signal }) => getEventList(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventListQueryResult = NonNullable<Awaited<ReturnType<typeof getEventList>>>
export type GetEventListQueryError = EventListResponse[]


export function useGetEventList<TData = Awaited<ReturnType<typeof getEventList>>, TError = EventListResponse[]>(
 params: undefined |  GetEventListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventList>>,
          TError,
          Awaited<ReturnType<typeof getEventList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventList<TData = Awaited<ReturnType<typeof getEventList>>, TError = EventListResponse[]>(
 params?: GetEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventList>>,
          TError,
          Awaited<ReturnType<typeof getEventList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventList<TData = Awaited<ReturnType<typeof getEventList>>, TError = EventListResponse[]>(
 params?: GetEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 행사 목록 조회
 */

export function useGetEventList<TData = Awaited<ReturnType<typeof getEventList>>, TError = EventListResponse[]>(
 params?: GetEventListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 새로운 행사를 생성합니다. 운영진 이상 권한 필요.
 * @summary 행사 생성
 */
export type createEventResponse201 = {
  data: EventCreateResponse
  status: 201
}

export type createEventResponse400 = {
  data: EventCreateResponse
  status: 400
}

export type createEventResponse401 = {
  data: EventCreateResponse
  status: 401
}

export type createEventResponse403 = {
  data: EventCreateResponse
  status: 403
}
    
export type createEventResponseSuccess = (createEventResponse201) & {
  headers: Headers;
};
export type createEventResponseError = (createEventResponse400 | createEventResponse401 | createEventResponse403) & {
  headers: Headers;
};

export type createEventResponse = (createEventResponseSuccess | createEventResponseError)

export const getCreateEventUrl = () => {


  

  return `/api/v1/events`
}

export const createEvent = async (createEventRequest: CreateEventRequest, options?: RequestInit): Promise<createEventResponse> => {
  
  return customFetch<createEventResponse>(getCreateEventUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventRequest,)
  }
);}




export const getCreateEventMutationOptions = <TError = EventCreateResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventRequest}, TContext> => {

const mutationKey = ['createEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEvent>>, {data: CreateEventRequest}> = (props) => {
          const {data} = props ?? {};

          return  createEvent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEventMutationResult = NonNullable<Awaited<ReturnType<typeof createEvent>>>
    export type CreateEventMutationBody = CreateEventRequest
    export type CreateEventMutationError = EventCreateResponse

    /**
 * @summary 행사 생성
 */
export const useCreateEvent = <TError = EventCreateResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEvent>>,
        TError,
        {data: CreateEventRequest},
        TContext
      > => {
      return useMutation(getCreateEventMutationOptions(options), queryClient);
    }
    /**
 * 행사를 수동으로 마감합니다. 작성자 또는 관리자만 가능합니다.
 * @summary 행사 수동 마감
 */
export type closeEventResponse200 = {
  data: EventDetailResponse
  status: 200
}

export type closeEventResponse400 = {
  data: EventDetailResponse
  status: 400
}

export type closeEventResponse401 = {
  data: EventDetailResponse
  status: 401
}

export type closeEventResponse403 = {
  data: EventDetailResponse
  status: 403
}
    
export type closeEventResponseSuccess = (closeEventResponse200) & {
  headers: Headers;
};
export type closeEventResponseError = (closeEventResponse400 | closeEventResponse401 | closeEventResponse403) & {
  headers: Headers;
};

export type closeEventResponse = (closeEventResponseSuccess | closeEventResponseError)

export const getCloseEventUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}/close`
}

export const closeEvent = async (eventId: number, options?: RequestInit): Promise<closeEventResponse> => {
  
  return customFetch<closeEventResponse>(getCloseEventUrl(eventId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getCloseEventMutationOptions = <TError = EventDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof closeEvent>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['closeEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeEvent>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  closeEvent(eventId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CloseEventMutationResult = NonNullable<Awaited<ReturnType<typeof closeEvent>>>
    
    export type CloseEventMutationError = EventDetailResponse

    /**
 * @summary 행사 수동 마감
 */
export const useCloseEvent = <TError = EventDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeEvent>>,
        TError,
        {eventId: number},
        TContext
      > => {
      return useMutation(getCloseEventMutationOptions(options), queryClient);
    }
    