/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePinnedPostRequest,
  PinnedPostDetailResponse,
  PinnedPostListResponse,
  UpdateDisplayOrderRequest
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 고정 게시글의 표시 순서를 변경합니다. OPERATOR 이상만 가능합니다.
 * @summary 고정 게시글 표시 순서 변경
 */
export type updateDisplayOrderResponse200 = {
  data: PinnedPostDetailResponse
  status: 200
}

export type updateDisplayOrderResponse400 = {
  data: PinnedPostDetailResponse
  status: 400
}

export type updateDisplayOrderResponse401 = {
  data: PinnedPostDetailResponse
  status: 401
}

export type updateDisplayOrderResponse403 = {
  data: PinnedPostDetailResponse
  status: 403
}

export type updateDisplayOrderResponse404 = {
  data: PinnedPostDetailResponse
  status: 404
}
    
export type updateDisplayOrderResponseSuccess = (updateDisplayOrderResponse200) & {
  headers: Headers;
};
export type updateDisplayOrderResponseError = (updateDisplayOrderResponse400 | updateDisplayOrderResponse401 | updateDisplayOrderResponse403 | updateDisplayOrderResponse404) & {
  headers: Headers;
};

export type updateDisplayOrderResponse = (updateDisplayOrderResponseSuccess | updateDisplayOrderResponseError)

export const getUpdateDisplayOrderUrl = (id: number,) => {


  

  return `/api/v1/pinned-posts/${id}/display-order`
}

export const updateDisplayOrder = async (id: number,
    updateDisplayOrderRequest: UpdateDisplayOrderRequest, options?: RequestInit): Promise<updateDisplayOrderResponse> => {
  
  return customFetch<updateDisplayOrderResponse>(getUpdateDisplayOrderUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDisplayOrderRequest,)
  }
);}




export const getUpdateDisplayOrderMutationOptions = <TError = PinnedPostDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDisplayOrder>>, TError,{id: number;data: UpdateDisplayOrderRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDisplayOrder>>, TError,{id: number;data: UpdateDisplayOrderRequest}, TContext> => {

const mutationKey = ['updateDisplayOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDisplayOrder>>, {id: number;data: UpdateDisplayOrderRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDisplayOrder(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDisplayOrderMutationResult = NonNullable<Awaited<ReturnType<typeof updateDisplayOrder>>>
    export type UpdateDisplayOrderMutationBody = UpdateDisplayOrderRequest
    export type UpdateDisplayOrderMutationError = PinnedPostDetailResponse

    /**
 * @summary 고정 게시글 표시 순서 변경
 */
export const useUpdateDisplayOrder = <TError = PinnedPostDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDisplayOrder>>, TError,{id: number;data: UpdateDisplayOrderRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDisplayOrder>>,
        TError,
        {id: number;data: UpdateDisplayOrderRequest},
        TContext
      > => {
      return useMutation(getUpdateDisplayOrderMutationOptions(options), queryClient);
    }
    /**
 * 메인 페이지에 고정된 모든 게시글을 표시 순서대로 조회합니다.
 * @summary 고정 게시글 목록 조회
 */
export type getPinnedPostListResponse200 = {
  data: PinnedPostListResponse[]
  status: 200
}
    
export type getPinnedPostListResponseSuccess = (getPinnedPostListResponse200) & {
  headers: Headers;
};
;

export type getPinnedPostListResponse = (getPinnedPostListResponseSuccess)

export const getGetPinnedPostListUrl = () => {


  

  return `/api/v1/pinned-posts`
}

export const getPinnedPostList = async ( options?: RequestInit): Promise<getPinnedPostListResponse> => {
  
  return customFetch<getPinnedPostListResponse>(getGetPinnedPostListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPinnedPostListQueryKey = () => {
    return [
    `/api/v1/pinned-posts`
    ] as const;
    }

    
export const getGetPinnedPostListQueryOptions = <TData = Awaited<ReturnType<typeof getPinnedPostList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPinnedPostList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPinnedPostListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPinnedPostList>>> = ({ signal }) => getPinnedPostList({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPinnedPostList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPinnedPostListQueryResult = NonNullable<Awaited<ReturnType<typeof getPinnedPostList>>>
export type GetPinnedPostListQueryError = unknown


export function useGetPinnedPostList<TData = Awaited<ReturnType<typeof getPinnedPostList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPinnedPostList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPinnedPostList>>,
          TError,
          Awaited<ReturnType<typeof getPinnedPostList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPinnedPostList<TData = Awaited<ReturnType<typeof getPinnedPostList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPinnedPostList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPinnedPostList>>,
          TError,
          Awaited<ReturnType<typeof getPinnedPostList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPinnedPostList<TData = Awaited<ReturnType<typeof getPinnedPostList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPinnedPostList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 고정 게시글 목록 조회
 */

export function useGetPinnedPostList<TData = Awaited<ReturnType<typeof getPinnedPostList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPinnedPostList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPinnedPostListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 게시글을 메인 페이지에 고정합니다. OPERATOR 이상만 가능합니다.
 * @summary 게시글 고정
 */
export type createPinnedPostResponse201 = {
  data: PinnedPostDetailResponse
  status: 201
}

export type createPinnedPostResponse400 = {
  data: PinnedPostDetailResponse
  status: 400
}

export type createPinnedPostResponse401 = {
  data: PinnedPostDetailResponse
  status: 401
}

export type createPinnedPostResponse403 = {
  data: PinnedPostDetailResponse
  status: 403
}

export type createPinnedPostResponse404 = {
  data: PinnedPostDetailResponse
  status: 404
}

export type createPinnedPostResponse409 = {
  data: PinnedPostDetailResponse
  status: 409
}
    
export type createPinnedPostResponseSuccess = (createPinnedPostResponse201) & {
  headers: Headers;
};
export type createPinnedPostResponseError = (createPinnedPostResponse400 | createPinnedPostResponse401 | createPinnedPostResponse403 | createPinnedPostResponse404 | createPinnedPostResponse409) & {
  headers: Headers;
};

export type createPinnedPostResponse = (createPinnedPostResponseSuccess | createPinnedPostResponseError)

export const getCreatePinnedPostUrl = () => {


  

  return `/api/v1/pinned-posts`
}

export const createPinnedPost = async (createPinnedPostRequest: CreatePinnedPostRequest, options?: RequestInit): Promise<createPinnedPostResponse> => {
  
  return customFetch<createPinnedPostResponse>(getCreatePinnedPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPinnedPostRequest,)
  }
);}




export const getCreatePinnedPostMutationOptions = <TError = PinnedPostDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPinnedPost>>, TError,{data: CreatePinnedPostRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPinnedPost>>, TError,{data: CreatePinnedPostRequest}, TContext> => {

const mutationKey = ['createPinnedPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPinnedPost>>, {data: CreatePinnedPostRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPinnedPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePinnedPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPinnedPost>>>
    export type CreatePinnedPostMutationBody = CreatePinnedPostRequest
    export type CreatePinnedPostMutationError = PinnedPostDetailResponse

    /**
 * @summary 게시글 고정
 */
export const useCreatePinnedPost = <TError = PinnedPostDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPinnedPost>>, TError,{data: CreatePinnedPostRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPinnedPost>>,
        TError,
        {data: CreatePinnedPostRequest},
        TContext
      > => {
      return useMutation(getCreatePinnedPostMutationOptions(options), queryClient);
    }
    /**
 * 게시글 고정을 해제합니다. OPERATOR 이상만 가능합니다.
 * @summary 게시글 고정 해제
 */
export type deletePinnedPostResponse204 = {
  data: void
  status: 204
}

export type deletePinnedPostResponse401 = {
  data: void
  status: 401
}

export type deletePinnedPostResponse403 = {
  data: void
  status: 403
}

export type deletePinnedPostResponse404 = {
  data: void
  status: 404
}
    
export type deletePinnedPostResponseSuccess = (deletePinnedPostResponse204) & {
  headers: Headers;
};
export type deletePinnedPostResponseError = (deletePinnedPostResponse401 | deletePinnedPostResponse403 | deletePinnedPostResponse404) & {
  headers: Headers;
};

export type deletePinnedPostResponse = (deletePinnedPostResponseSuccess | deletePinnedPostResponseError)

export const getDeletePinnedPostUrl = (id: number,) => {


  

  return `/api/v1/pinned-posts/${id}`
}

export const deletePinnedPost = async (id: number, options?: RequestInit): Promise<deletePinnedPostResponse> => {
  
  return customFetch<deletePinnedPostResponse>(getDeletePinnedPostUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeletePinnedPostMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePinnedPost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePinnedPost>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePinnedPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePinnedPost>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePinnedPost(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePinnedPostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePinnedPost>>>
    
    export type DeletePinnedPostMutationError = void

    /**
 * @summary 게시글 고정 해제
 */
export const useDeletePinnedPost = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePinnedPost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePinnedPost>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePinnedPostMutationOptions(options), queryClient);
    }
    