/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  SubmitAnonymousResponse201,
  SubmitAnonymousResponseBody
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 비회원이 PUBLIC 설문에 응답을 제출합니다. 인증 없이 접근 가능합니다.
 * @summary 비회원 설문 응답 제출
 */
export type submitAnonymousResponseResponse201 = {
  data: SubmitAnonymousResponse201
  status: 201
}

export type submitAnonymousResponseResponse400 = {
  data: void
  status: 400
}

export type submitAnonymousResponseResponse403 = {
  data: void
  status: 403
}

export type submitAnonymousResponseResponse404 = {
  data: void
  status: 404
}
    
export type submitAnonymousResponseResponseSuccess = (submitAnonymousResponseResponse201) & {
  headers: Headers;
};
export type submitAnonymousResponseResponseError = (submitAnonymousResponseResponse400 | submitAnonymousResponseResponse403 | submitAnonymousResponseResponse404) & {
  headers: Headers;
};

export type submitAnonymousResponseResponse = (submitAnonymousResponseResponseSuccess | submitAnonymousResponseResponseError)

export const getSubmitAnonymousResponseUrl = (surveyId: number,) => {


  

  return `/api/v1/surveys/${surveyId}/responses/anonymous`
}

export const submitAnonymousResponse = async (surveyId: number,
    submitAnonymousResponseBody: SubmitAnonymousResponseBody, options?: RequestInit): Promise<submitAnonymousResponseResponse> => {
  
  return customFetch<submitAnonymousResponseResponse>(getSubmitAnonymousResponseUrl(surveyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submitAnonymousResponseBody,)
  }
);}




export const getSubmitAnonymousResponseMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitAnonymousResponse>>, TError,{surveyId: number;data: SubmitAnonymousResponseBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitAnonymousResponse>>, TError,{surveyId: number;data: SubmitAnonymousResponseBody}, TContext> => {

const mutationKey = ['submitAnonymousResponse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitAnonymousResponse>>, {surveyId: number;data: SubmitAnonymousResponseBody}> = (props) => {
          const {surveyId,data} = props ?? {};

          return  submitAnonymousResponse(surveyId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitAnonymousResponseMutationResult = NonNullable<Awaited<ReturnType<typeof submitAnonymousResponse>>>
    export type SubmitAnonymousResponseMutationBody = SubmitAnonymousResponseBody
    export type SubmitAnonymousResponseMutationError = void

    /**
 * @summary 비회원 설문 응답 제출
 */
export const useSubmitAnonymousResponse = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitAnonymousResponse>>, TError,{surveyId: number;data: SubmitAnonymousResponseBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitAnonymousResponse>>,
        TError,
        {surveyId: number;data: SubmitAnonymousResponseBody},
        TContext
      > => {
      return useMutation(getSubmitAnonymousResponseMutationOptions(options), queryClient);
    }
    