/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetHistoriesParams,
  Page,
  PageAccountStatusChangeHistoryResponse
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 계정 상태 변경 감사 이력을 조회합니다. 사용자, 변경자, 변경 유형, 기간으로 필터링 가능합니다.
 * @summary 계정 상태 변경 감사 이력 조회
 */
export type getHistoriesResponse200 = {
  data: Page
  status: 200
}

export type getHistoriesResponse401 = {
  data: PageAccountStatusChangeHistoryResponse
  status: 401
}

export type getHistoriesResponse403 = {
  data: PageAccountStatusChangeHistoryResponse
  status: 403
}
    
export type getHistoriesResponseSuccess = (getHistoriesResponse200) & {
  headers: Headers;
};
export type getHistoriesResponseError = (getHistoriesResponse401 | getHistoriesResponse403) & {
  headers: Headers;
};

export type getHistoriesResponse = (getHistoriesResponseSuccess | getHistoriesResponseError)

export const getGetHistoriesUrl = (params?: GetHistoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/account-status-histories?${stringifiedParams}` : `/api/v1/admin/account-status-histories`
}

export const getHistories = async (params?: GetHistoriesParams, options?: RequestInit): Promise<getHistoriesResponse> => {
  
  return customFetch<getHistoriesResponse>(getGetHistoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHistoriesQueryKey = (params?: GetHistoriesParams,) => {
    return [
    `/api/v1/admin/account-status-histories`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetHistoriesQueryOptions = <TData = Awaited<ReturnType<typeof getHistories>>, TError = PageAccountStatusChangeHistoryResponse>(params?: GetHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistories>>> = ({ signal }) => getHistories(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHistoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getHistories>>>
export type GetHistoriesQueryError = PageAccountStatusChangeHistoryResponse


export function useGetHistories<TData = Awaited<ReturnType<typeof getHistories>>, TError = PageAccountStatusChangeHistoryResponse>(
 params: undefined |  GetHistoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistories>>,
          TError,
          Awaited<ReturnType<typeof getHistories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistories<TData = Awaited<ReturnType<typeof getHistories>>, TError = PageAccountStatusChangeHistoryResponse>(
 params?: GetHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistories>>,
          TError,
          Awaited<ReturnType<typeof getHistories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistories<TData = Awaited<ReturnType<typeof getHistories>>, TError = PageAccountStatusChangeHistoryResponse>(
 params?: GetHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 계정 상태 변경 감사 이력 조회
 */

export function useGetHistories<TData = Awaited<ReturnType<typeof getHistories>>, TError = PageAccountStatusChangeHistoryResponse>(
 params?: GetHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHistoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




