/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import type { EditUserInfoBodyEnrollmentStatus } from './editUserInfoBodyEnrollmentStatus';
import type { EditUserInfoBodyGender } from './editUserInfoBodyGender';
import type { EditUserInfoBodyInterestsItem } from './editUserInfoBodyInterestsItem';
import type { EditUserInfoBodyJoinRoute } from './editUserInfoBodyJoinRoute';
import type { EditUserInfoBodyWishesItem } from './editUserInfoBodyWishesItem';

/**
 * 관리자 회원 정보 수정 요청 (부분 업데이트: null 필드는 기존 값 유지)
 */
export type EditUserInfoBody = {
  /**
   * 학번 (null이면 변경하지 않음)
   * @pattern ^\d{8}$
   */
  studentId?: string;
  /** 이메일 (null이면 변경하지 않음) */
  email?: string;
  /**
   * 이름 (null이면 변경하지 않음)
   * @minLength 1
   * @maxLength 50
   */
  name?: string;
  /** 전화번호 (null이면 변경하지 않음) */
  phoneNumber?: string;
  /**
   * 학과 (null이면 변경하지 않음)
   * @minLength 0
   * @maxLength 50
   */
  department?: string;
  /** 성별 (null이면 변경하지 않음) */
  gender?: EditUserInfoBodyGender;
  /**
   * 학년 (null이면 변경하지 않음)
   * @minimum 1
   * @maximum 4
   */
  grade?: number;
  /** 재학 상태 (null이면 변경하지 않음) */
  enrollmentStatus?: EditUserInfoBodyEnrollmentStatus;
  /** 가입 동기 (null이면 변경하지 않음) */
  motivation?: string;
  /** 가입 목적 (null이면 변경하지 않음) */
  wishes?: EditUserInfoBodyWishesItem[];
  /** 관심 분야 (null이면 변경하지 않음) */
  interests?: EditUserInfoBodyInterestsItem[];
  /**
   * 기타 관심 분야 (null이면 변경하지 않음)
   * @minLength 0
   * @maxLength 100
   */
  customInterest?: string;
  /** 가입 경로 (null이면 변경하지 않음) */
  joinRoute?: EditUserInfoBodyJoinRoute;
  /**
   * 기타 가입 경로 (null이면 변경하지 않음)
   * @minLength 0
   * @maxLength 100
   */
  customJoinRoute?: string;
};
