/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import type { SubmitAnswerRequest } from "./submitAnswerRequest";

/**
 * 외부인(비회원) 행사 신청 요청.
학번과 전화번호 각각 동일 행사 내 중복 신청을 방지합니다.
설문 연결 행사의 경우 surveyAnswers를 포함하여 설문 응답과 행사 신청을 원자적으로 처리합니다.

 */
export interface ExternalRegisterEventRequest {
  /**
   * 신청자 이름
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /**
   * 신청자 학번 (중복 방지 식별자)
   * @minLength 1
   * @maxLength 20
   */
  studentId: string;
  /**
   * 신청자 연락처 (중복 방지 식별자)
   * @minLength 1
   * @maxLength 20
   */
  phone: string;
  /**
   * 신청자 학과
   * @minLength 1
   * @maxLength 100
   */
  department: string;
  /**
   * 설문 응답 배열. 설문 연결 행사 신청 시 설문 응답을 포함합니다.
   * @nullable
   */
  surveyAnswers?: SubmitAnswerRequest[] | null;
}
