/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import type { GetMyInquiry404AttachmentsItem } from './getMyInquiry404AttachmentsItem';
import type { GetMyInquiry404Reply } from './getMyInquiry404Reply';
import type { GetMyInquiry404Status } from './getMyInquiry404Status';
import type { GetMyInquiry404Type } from './getMyInquiry404Type';

/**
 * 문의 응답
 */
export type GetMyInquiry404 = {
  /** 문의 고유 ID */
  id?: number;
  /** 문의 번호 */
  inquiryNumber?: string;
  /** 문의 유형 */
  type?: GetMyInquiry404Type;
  /** 문의 유형 설명 */
  typeDescription?: string;
  /** 문의 상태 */
  status?: GetMyInquiry404Status;
  /** 문의 상태 설명 */
  statusDescription?: string;
  /** 문의 제목 */
  title?: string;
  /** 문의 내용 */
  content?: string;
  /** 작성자 이름 */
  authorName?: string;
  /** 작성자 이메일 */
  authorEmail?: string;
  /** 첨부파일 목록 */
  attachments?: GetMyInquiry404AttachmentsItem[];
  /** 문의 답변 응답 */
  reply?: GetMyInquiry404Reply;
  /** 문의 작성 일시 */
  createdAt?: string;
  /** 문의 수정 일시 */
  updatedAt?: string;
  guest?: boolean;
};
