/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import type { GetMemberList401ItemRole } from './getMemberList401ItemRole';

/**
 * 학기별 회원 목록 응답
 */
export type GetMemberList401Item = {
  /** 사용자 ID */
  userId?: number;
  /** 학번 (등록 시점 스냅샷) */
  studentId?: string;
  /** 이름 (등록 시점 스냅샷) */
  name?: string;
  /** 학과 (등록 시점 스냅샷) */
  department?: string;
  /** 이메일 */
  email?: string;
  /** 전화번호 */
  phoneNumber?: string;
  /** 등록 시점 역할 */
  role?: GetMemberList401ItemRole;
  /** 탈퇴 여부 */
  isWithdrawn?: boolean;
  /** 학년 (등록 시점 스냅샷) */
  grade?: number;
  /** 가입 동기 (등록 시점 스냅샷) */
  motivation?: string;
};
