/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import type { GetUserDetail404EnrollmentStatus } from './getUserDetail404EnrollmentStatus';
import type { GetUserDetail404Gender } from './getUserDetail404Gender';
import type { GetUserDetail404InterestsItem } from './getUserDetail404InterestsItem';
import type { GetUserDetail404JoinRoute } from './getUserDetail404JoinRoute';
import type { GetUserDetail404Role } from './getUserDetail404Role';
import type { GetUserDetail404Status } from './getUserDetail404Status';
import type { GetUserDetail404WishesItem } from './getUserDetail404WishesItem';

/**
 * 관리자용 회원 상세 응답
 */
export type GetUserDetail404 = {
  /** 사용자 ID */
  userId?: number;
  /** 학번 */
  studentId?: string;
  /** 이름 */
  name?: string;
  /** 이메일 */
  email?: string;
  /** 전화번호 */
  phoneNumber?: string;
  /** 학과 */
  department?: string;
  /** 가입 동기 */
  motivation?: string;
  /** 가입 목적 */
  wishes?: GetUserDetail404WishesItem[];
  /** 관심 분야 */
  interests?: GetUserDetail404InterestsItem[];
  /** 기타 관심 분야 */
  customInterest?: string;
  /** 가입 경로 */
  joinRoute?: GetUserDetail404JoinRoute;
  /** 기타 가입 경로 */
  customJoinRoute?: string;
  /** 성별 */
  gender?: GetUserDetail404Gender;
  /** 학년 */
  grade?: number;
  /** 재학 상태 */
  enrollmentStatus?: GetUserDetail404EnrollmentStatus;
  /** 역할 */
  role?: GetUserDetail404Role;
  /** 상태 */
  status?: GetUserDetail404Status;
  /** 가입일 */
  createdAt?: string;
};
