/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import type { PasswordSignupRequestGender } from './passwordSignupRequestGender';

/**
 * 비밀번호 기반 회원가입 요청
 */
export interface PasswordSignupRequest {
  /**
   * 학번 (8자리 숫자)
   * @minLength 1
   * @pattern ^\d{8}$
   */
  studentId: string;
  /**
   * 사용자 이름
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /**
   * 이메일 주소
   * @minLength 1
   */
  email: string;
  /**
   * 비밀번호 (영문 대/소문자, 숫자, 특수문자 포함 8~72자)
   * @minLength 8
   * @maxLength 72
   * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,72}$
   */
  password: string;
  /**
   * 전화번호
   * @minLength 1
   * @pattern ^01[0-9]-?\d{3,4}-?\d{4}$
   */
  phoneNumber: string;
  /**
   * 학과명
   * @minLength 0
   * @maxLength 50
   */
  department: string;
  /**
   * 동아리 가입 동기
   * @minLength 1
   */
  motivation: string;
  /** 성별 */
  gender: PasswordSignupRequestGender;
  /**
   * 학년 (1 이상)
   * @minimum 1
   */
  grade: number;
  /** 개인정보 처리방침 동의 여부 */
  privacyConsent: boolean;
}
