/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import type { RegistrationListResponseStatus } from "./registrationListResponseStatus";

export interface RegistrationListResponse {
  registrationId?: number;
  /**
   * 회원 신청자의 사용자 ID (외부인 신청의 경우 null)
   * @nullable
   */
  userId?: number | null;
  /** 신청자 이름 */
  userName?: string;
  /**
   * 신청자 이메일 (외부인 신청의 경우 null)
   * @nullable
   */
  userEmail?: string | null;
  /**
   * 학번
   * @nullable
   */
  studentId?: string | null;
  /**
   * 성별 (외부인의 경우 null)
   * @nullable
   */
  userGender?: string | null;
  /**
   * 학년 (외부인의 경우 null)
   * @nullable
   */
  userGrade?: number | null;
  /**
   * 학과
   * @nullable
   */
  userDepartment?: string | null;
  /**
   * 연락처 (외부인의 경우에만 표시)
   * @nullable
   */
  phone?: string | null;
  /** 외부인 신청 여부 */
  isExternal?: boolean;
  status?: RegistrationListResponseStatus;
  registeredAt?: string;
}
