/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DashboardStatsResponse
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 오늘 게시글/댓글 수, 이번 주 정회원 승인 수, 대기 중 문의 수, 승인 대기 준회원 수를 조회합니다.
 * @summary 대시보드 통계 조회
 */
export type getDashboardStatsResponse200 = {
  data: DashboardStatsResponse
  status: 200
}

export type getDashboardStatsResponse401 = {
  data: DashboardStatsResponse
  status: 401
}

export type getDashboardStatsResponse403 = {
  data: DashboardStatsResponse
  status: 403
}
    
export type getDashboardStatsResponseSuccess = (getDashboardStatsResponse200) & {
  headers: Headers;
};
export type getDashboardStatsResponseError = (getDashboardStatsResponse401 | getDashboardStatsResponse403) & {
  headers: Headers;
};

export type getDashboardStatsResponse = (getDashboardStatsResponseSuccess | getDashboardStatsResponseError)

export const getGetDashboardStatsUrl = () => {


  

  return `/api/v1/admin/dashboard`
}

export const getDashboardStats = async ( options?: RequestInit): Promise<getDashboardStatsResponse> => {
  
  return customFetch<getDashboardStatsResponse>(getGetDashboardStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDashboardStatsQueryKey = () => {
    return [
    `/api/v1/admin/dashboard`
    ] as const;
    }

    
export const getGetDashboardStatsQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = DashboardStatsResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardStats>>> = ({ signal }) => getDashboardStats({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardStats>>>
export type GetDashboardStatsQueryError = DashboardStatsResponse


export function useGetDashboardStats<TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = DashboardStatsResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStats>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardStats<TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = DashboardStatsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStats>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardStats<TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = DashboardStatsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 대시보드 통계 조회
 */

export function useGetDashboardStats<TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = DashboardStatsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




