/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AdminSurveyResponseListItem } from ".././models";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 관리자가 특정 설문에 제출된 응답 목록을 조회합니다. OPERATOR 이상 권한 필요.
 * @summary 관리자 설문 응답 목록 조회
 */
export type getAdminSurveyResponsesResponse200 = {
  data: AdminSurveyResponseListItem[];
  status: 200;
};

export type getAdminSurveyResponsesResponse401 = {
  data: void;
  status: 401;
};

export type getAdminSurveyResponsesResponse403 = {
  data: void;
  status: 403;
};

export type getAdminSurveyResponsesResponse404 = {
  data: void;
  status: 404;
};

export type getAdminSurveyResponsesResponseSuccess =
  getAdminSurveyResponsesResponse200 & {
    headers: Headers;
  };
export type getAdminSurveyResponsesResponseError = (
  | getAdminSurveyResponsesResponse401
  | getAdminSurveyResponsesResponse403
  | getAdminSurveyResponsesResponse404
) & {
  headers: Headers;
};

export type getAdminSurveyResponsesResponse =
  | getAdminSurveyResponsesResponseSuccess
  | getAdminSurveyResponsesResponseError;

export const getGetAdminSurveyResponsesUrl = (surveyId: number) => {
  return `/api/v1/admin/surveys/${surveyId}/responses`;
};

export const getAdminSurveyResponses = async (
  surveyId: number,
  options?: RequestInit,
): Promise<getAdminSurveyResponsesResponse> => {
  return customFetch<getAdminSurveyResponsesResponse>(
    getGetAdminSurveyResponsesUrl(surveyId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAdminSurveyResponsesQueryKey = (surveyId: number) => {
  return [`/api/v1/admin/surveys/${surveyId}/responses`] as const;
};

export const getGetAdminSurveyResponsesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminSurveyResponses>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminSurveyResponses>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminSurveyResponsesQueryKey(surveyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminSurveyResponses>>
  > = ({ signal }) =>
    getAdminSurveyResponses(surveyId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!surveyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminSurveyResponses>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminSurveyResponsesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminSurveyResponses>>
>;
export type GetAdminSurveyResponsesQueryError = void;

export function useGetAdminSurveyResponses<
  TData = Awaited<ReturnType<typeof getAdminSurveyResponses>>,
  TError = void,
>(
  surveyId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminSurveyResponses>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSurveyResponses>>,
          TError,
          Awaited<ReturnType<typeof getAdminSurveyResponses>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminSurveyResponses<
  TData = Awaited<ReturnType<typeof getAdminSurveyResponses>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminSurveyResponses>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSurveyResponses>>,
          TError,
          Awaited<ReturnType<typeof getAdminSurveyResponses>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminSurveyResponses<
  TData = Awaited<ReturnType<typeof getAdminSurveyResponses>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminSurveyResponses>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 관리자 설문 응답 목록 조회
 */

export function useGetAdminSurveyResponses<
  TData = Awaited<ReturnType<typeof getAdminSurveyResponses>>,
  TError = void,
>(
  surveyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminSurveyResponses>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminSurveyResponsesQueryOptions(
    surveyId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
