/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  SsoAuthorizeParams,
  SsoTokenRequest,
  SsoTokenResponse,
} from ".././models";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 브라우저 top-level 리다이렉트로 호출됩니다. refresh 쿠키로 로그인 상태를 확인하고, 로그인되어 있으면 일회용 코드를 redirect_uri에 sso_code 쿼리로 붙여 리다이렉트합니다. 비로그인이면 sso=none으로 리다이렉트합니다. redirect_uri의 origin은 서버 허용 목록에 있어야 합니다.
 * @summary SSO 인가 (일회용 코드 발급)
 */
export type ssoAuthorizeResponse302 = {
  data: void;
  status: 302;
};

export type ssoAuthorizeResponse400 = {
  data: void;
  status: 400;
};
export type ssoAuthorizeResponseError = (
  | ssoAuthorizeResponse302
  | ssoAuthorizeResponse400
) & {
  headers: Headers;
};

export type ssoAuthorizeResponse = ssoAuthorizeResponseError;

export const getSsoAuthorizeUrl = (params: SsoAuthorizeParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/auth/sso/authorize?${stringifiedParams}`
    : `/api/v1/auth/sso/authorize`;
};

export const ssoAuthorize = async (
  params: SsoAuthorizeParams,
  options?: RequestInit,
): Promise<ssoAuthorizeResponse> => {
  return customFetch<ssoAuthorizeResponse>(getSsoAuthorizeUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSsoAuthorizeQueryKey = (params?: SsoAuthorizeParams) => {
  return [`/api/v1/auth/sso/authorize`, ...(params ? [params] : [])] as const;
};

export const getSsoAuthorizeQueryOptions = <
  TData = Awaited<ReturnType<typeof ssoAuthorize>>,
  TError = void,
>(
  params: SsoAuthorizeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ssoAuthorize>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSsoAuthorizeQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof ssoAuthorize>>> = ({
    signal,
  }) => ssoAuthorize(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof ssoAuthorize>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SsoAuthorizeQueryResult = NonNullable<
  Awaited<ReturnType<typeof ssoAuthorize>>
>;
export type SsoAuthorizeQueryError = void;

export function useSsoAuthorize<
  TData = Awaited<ReturnType<typeof ssoAuthorize>>,
  TError = void,
>(
  params: SsoAuthorizeParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ssoAuthorize>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ssoAuthorize>>,
          TError,
          Awaited<ReturnType<typeof ssoAuthorize>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSsoAuthorize<
  TData = Awaited<ReturnType<typeof ssoAuthorize>>,
  TError = void,
>(
  params: SsoAuthorizeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ssoAuthorize>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ssoAuthorize>>,
          TError,
          Awaited<ReturnType<typeof ssoAuthorize>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSsoAuthorize<
  TData = Awaited<ReturnType<typeof ssoAuthorize>>,
  TError = void,
>(
  params: SsoAuthorizeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ssoAuthorize>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary SSO 인가 (일회용 코드 발급)
 */

export function useSsoAuthorize<
  TData = Awaited<ReturnType<typeof ssoAuthorize>>,
  TError = void,
>(
  params: SsoAuthorizeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ssoAuthorize>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSsoAuthorizeQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * ssoAuthorize가 발급한 일회용 코드를 액세스 토큰과 새 리프레시 토큰(새 토큰 패밀리)으로 교환합니다. 코드는 60초 내 1회만 사용할 수 있습니다. 서비스 백엔드(server-to-server) 호출용입니다.
 * @summary SSO 일회용 코드 → 토큰 교환
 */
export type ssoIssueTokenResponse200 = {
  data: SsoTokenResponse;
  status: 200;
};

export type ssoIssueTokenResponse400 = {
  data: void;
  status: 400;
};

export type ssoIssueTokenResponse401 = {
  data: void;
  status: 401;
};

export type ssoIssueTokenResponseSuccess = ssoIssueTokenResponse200 & {
  headers: Headers;
};
export type ssoIssueTokenResponseError = (
  | ssoIssueTokenResponse400
  | ssoIssueTokenResponse401
) & {
  headers: Headers;
};

export type ssoIssueTokenResponse =
  | ssoIssueTokenResponseSuccess
  | ssoIssueTokenResponseError;

export const getSsoIssueTokenUrl = () => {
  return `/api/v1/auth/sso/token`;
};

export const ssoIssueToken = async (
  ssoTokenRequest: SsoTokenRequest,
  options?: RequestInit,
): Promise<ssoIssueTokenResponse> => {
  return customFetch<ssoIssueTokenResponse>(getSsoIssueTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ssoTokenRequest),
  });
};

export const getSsoIssueTokenMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ssoIssueToken>>,
    TError,
    { data: SsoTokenRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ssoIssueToken>>,
  TError,
  { data: SsoTokenRequest },
  TContext
> => {
  const mutationKey = ["ssoIssueToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ssoIssueToken>>,
    { data: SsoTokenRequest }
  > = (props) => {
    const { data } = props ?? {};

    return ssoIssueToken(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SsoIssueTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof ssoIssueToken>>
>;
export type SsoIssueTokenMutationBody = SsoTokenRequest;
export type SsoIssueTokenMutationError = void;

/**
 * @summary SSO 일회용 코드 → 토큰 교환
 */
export const useSsoIssueToken = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ssoIssueToken>>,
      TError,
      { data: SsoTokenRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof ssoIssueToken>>,
  TError,
  { data: SsoTokenRequest },
  TContext
> => {
  return useMutation(getSsoIssueTokenMutationOptions(options), queryClient);
};
