/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  MyRegistrationResponse,
  RegistrationListResponse,
  RegistrationResponse
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 신청을 거절합니다. (선발제) 작성자 또는 관리자만 가능합니다.
 * @summary 신청 거절
 */
export type rejectRegistrationResponse200 = {
  data: RegistrationResponse
  status: 200
}

export type rejectRegistrationResponse401 = {
  data: ErrorResponse
  status: 401
}

export type rejectRegistrationResponse403 = {
  data: ErrorResponse
  status: 403
}

export type rejectRegistrationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type rejectRegistrationResponseSuccess = (rejectRegistrationResponse200) & {
  headers: Headers;
};
export type rejectRegistrationResponseError = (rejectRegistrationResponse401 | rejectRegistrationResponse403 | rejectRegistrationResponse404) & {
  headers: Headers;
};

export type rejectRegistrationResponse = (rejectRegistrationResponseSuccess | rejectRegistrationResponseError)

export const getRejectRegistrationUrl = (registrationId: number,) => {


  

  return `/api/v1/registrations/${registrationId}/reject`
}

export const rejectRegistration = async (registrationId: number, options?: RequestInit): Promise<rejectRegistrationResponse> => {
  
  return customFetch<rejectRegistrationResponse>(getRejectRegistrationUrl(registrationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRejectRegistrationMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectRegistration>>, TError,{registrationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof rejectRegistration>>, TError,{registrationId: number}, TContext> => {

const mutationKey = ['rejectRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectRegistration>>, {registrationId: number}> = (props) => {
          const {registrationId} = props ?? {};

          return  rejectRegistration(registrationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RejectRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof rejectRegistration>>>
    
    export type RejectRegistrationMutationError = ErrorResponse

    /**
 * @summary 신청 거절
 */
export const useRejectRegistration = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectRegistration>>, TError,{registrationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectRegistration>>,
        TError,
        {registrationId: number},
        TContext
      > => {
      return useMutation(getRejectRegistrationMutationOptions(options), queryClient);
    }
    /**
 * 신청을 승인합니다. (선발제) 작성자 또는 관리자만 가능합니다.
 * @summary 신청 승인
 */
export type approveRegistrationResponse200 = {
  data: RegistrationResponse
  status: 200
}

export type approveRegistrationResponse401 = {
  data: ErrorResponse
  status: 401
}

export type approveRegistrationResponse403 = {
  data: ErrorResponse
  status: 403
}

export type approveRegistrationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type approveRegistrationResponseSuccess = (approveRegistrationResponse200) & {
  headers: Headers;
};
export type approveRegistrationResponseError = (approveRegistrationResponse401 | approveRegistrationResponse403 | approveRegistrationResponse404) & {
  headers: Headers;
};

export type approveRegistrationResponse = (approveRegistrationResponseSuccess | approveRegistrationResponseError)

export const getApproveRegistrationUrl = (registrationId: number,) => {


  

  return `/api/v1/registrations/${registrationId}/approve`
}

export const approveRegistration = async (registrationId: number, options?: RequestInit): Promise<approveRegistrationResponse> => {
  
  return customFetch<approveRegistrationResponse>(getApproveRegistrationUrl(registrationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getApproveRegistrationMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveRegistration>>, TError,{registrationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approveRegistration>>, TError,{registrationId: number}, TContext> => {

const mutationKey = ['approveRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveRegistration>>, {registrationId: number}> = (props) => {
          const {registrationId} = props ?? {};

          return  approveRegistration(registrationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ApproveRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof approveRegistration>>>
    
    export type ApproveRegistrationMutationError = ErrorResponse

    /**
 * @summary 신청 승인
 */
export const useApproveRegistration = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveRegistration>>, TError,{registrationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveRegistration>>,
        TError,
        {registrationId: number},
        TContext
      > => {
      return useMutation(getApproveRegistrationMutationOptions(options), queryClient);
    }
    /**
 * 행사 신청자 목록을 조회합니다. 작성자 또는 관리자만 가능합니다.
 * @summary 신청자 목록 조회
 */
export type getRegistrationListResponse200 = {
  data: RegistrationListResponse[]
  status: 200
}

export type getRegistrationListResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getRegistrationListResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getRegistrationListResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getRegistrationListResponseSuccess = (getRegistrationListResponse200) & {
  headers: Headers;
};
export type getRegistrationListResponseError = (getRegistrationListResponse401 | getRegistrationListResponse403 | getRegistrationListResponse404) & {
  headers: Headers;
};

export type getRegistrationListResponse = (getRegistrationListResponseSuccess | getRegistrationListResponseError)

export const getGetRegistrationListUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}/registrations`
}

export const getRegistrationList = async (eventId: number, options?: RequestInit): Promise<getRegistrationListResponse> => {
  
  return customFetch<getRegistrationListResponse>(getGetRegistrationListUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetRegistrationListQueryKey = (eventId: number,) => {
    return [
    `/api/v1/events/${eventId}/registrations`
    ] as const;
    }

    
export const getGetRegistrationListQueryOptions = <TData = Awaited<ReturnType<typeof getRegistrationList>>, TError = ErrorResponse>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRegistrationListQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegistrationList>>> = ({ signal }) => getRegistrationList(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRegistrationList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRegistrationListQueryResult = NonNullable<Awaited<ReturnType<typeof getRegistrationList>>>
export type GetRegistrationListQueryError = ErrorResponse


export function useGetRegistrationList<TData = Awaited<ReturnType<typeof getRegistrationList>>, TError = ErrorResponse>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegistrationList>>,
          TError,
          Awaited<ReturnType<typeof getRegistrationList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegistrationList<TData = Awaited<ReturnType<typeof getRegistrationList>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegistrationList>>,
          TError,
          Awaited<ReturnType<typeof getRegistrationList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegistrationList<TData = Awaited<ReturnType<typeof getRegistrationList>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 신청자 목록 조회
 */

export function useGetRegistrationList<TData = Awaited<ReturnType<typeof getRegistrationList>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRegistrationListQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 행사에 신청합니다. 정회원 이상만 가능합니다.
 * @summary 행사 신청
 */
export type registerEventResponse201 = {
  data: RegistrationResponse
  status: 201
}

export type registerEventResponse400 = {
  data: ErrorResponse
  status: 400
}

export type registerEventResponse401 = {
  data: ErrorResponse
  status: 401
}

export type registerEventResponse403 = {
  data: ErrorResponse
  status: 403
}

export type registerEventResponse404 = {
  data: ErrorResponse
  status: 404
}

export type registerEventResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type registerEventResponseSuccess = (registerEventResponse201) & {
  headers: Headers;
};
export type registerEventResponseError = (registerEventResponse400 | registerEventResponse401 | registerEventResponse403 | registerEventResponse404 | registerEventResponse409) & {
  headers: Headers;
};

export type registerEventResponse = (registerEventResponseSuccess | registerEventResponseError)

export const getRegisterEventUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}/registrations`
}

export const registerEvent = async (eventId: number, options?: RequestInit): Promise<registerEventResponse> => {
  
  return customFetch<registerEventResponse>(getRegisterEventUrl(eventId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRegisterEventMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof registerEvent>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['registerEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerEvent>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  registerEvent(eventId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterEventMutationResult = NonNullable<Awaited<ReturnType<typeof registerEvent>>>
    
    export type RegisterEventMutationError = ErrorResponse

    /**
 * @summary 행사 신청
 */
export const useRegisterEvent = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerEvent>>,
        TError,
        {eventId: number},
        TContext
      > => {
      return useMutation(getRegisterEventMutationOptions(options), queryClient);
    }
    /**
 * 행사 신청을 취소합니다.
 * @summary 신청 취소
 */
export type cancelRegistrationResponse200 = {
  data: RegistrationResponse
  status: 200
}

export type cancelRegistrationResponse401 = {
  data: ErrorResponse
  status: 401
}

export type cancelRegistrationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type cancelRegistrationResponseSuccess = (cancelRegistrationResponse200) & {
  headers: Headers;
};
export type cancelRegistrationResponseError = (cancelRegistrationResponse401 | cancelRegistrationResponse404) & {
  headers: Headers;
};

export type cancelRegistrationResponse = (cancelRegistrationResponseSuccess | cancelRegistrationResponseError)

export const getCancelRegistrationUrl = (eventId: number,) => {


  

  return `/api/v1/events/${eventId}/registrations`
}

export const cancelRegistration = async (eventId: number, options?: RequestInit): Promise<cancelRegistrationResponse> => {
  
  return customFetch<cancelRegistrationResponse>(getCancelRegistrationUrl(eventId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCancelRegistrationMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelRegistration>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelRegistration>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['cancelRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelRegistration>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  cancelRegistration(eventId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof cancelRegistration>>>
    
    export type CancelRegistrationMutationError = ErrorResponse

    /**
 * @summary 신청 취소
 */
export const useCancelRegistration = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelRegistration>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelRegistration>>,
        TError,
        {eventId: number},
        TContext
      > => {
      return useMutation(getCancelRegistrationMutationOptions(options), queryClient);
    }
    /**
 * 내가 신청한 행사 목록을 조회합니다.
 * @summary 내 신청 목록 조회
 */
export type getMyRegistrations1Response200 = {
  data: MyRegistrationResponse[]
  status: 200
}

export type getMyRegistrations1Response401 = {
  data: ErrorResponse
  status: 401
}
    
export type getMyRegistrations1ResponseSuccess = (getMyRegistrations1Response200) & {
  headers: Headers;
};
export type getMyRegistrations1ResponseError = (getMyRegistrations1Response401) & {
  headers: Headers;
};

export type getMyRegistrations1Response = (getMyRegistrations1ResponseSuccess | getMyRegistrations1ResponseError)

export const getGetMyRegistrations1Url = () => {


  

  return `/api/v1/my/registrations`
}

export const getMyRegistrations1 = async ( options?: RequestInit): Promise<getMyRegistrations1Response> => {
  
  return customFetch<getMyRegistrations1Response>(getGetMyRegistrations1Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyRegistrations1QueryKey = () => {
    return [
    `/api/v1/my/registrations`
    ] as const;
    }

    
export const getGetMyRegistrations1QueryOptions = <TData = Awaited<ReturnType<typeof getMyRegistrations1>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRegistrations1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyRegistrations1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyRegistrations1>>> = ({ signal }) => getMyRegistrations1({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyRegistrations1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyRegistrations1QueryResult = NonNullable<Awaited<ReturnType<typeof getMyRegistrations1>>>
export type GetMyRegistrations1QueryError = ErrorResponse


export function useGetMyRegistrations1<TData = Awaited<ReturnType<typeof getMyRegistrations1>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRegistrations1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyRegistrations1>>,
          TError,
          Awaited<ReturnType<typeof getMyRegistrations1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyRegistrations1<TData = Awaited<ReturnType<typeof getMyRegistrations1>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRegistrations1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyRegistrations1>>,
          TError,
          Awaited<ReturnType<typeof getMyRegistrations1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyRegistrations1<TData = Awaited<ReturnType<typeof getMyRegistrations1>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRegistrations1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 신청 목록 조회
 */

export function useGetMyRegistrations1<TData = Awaited<ReturnType<typeof getMyRegistrations1>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRegistrations1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyRegistrations1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




