/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CreateGuestInquiryRequest,
  GuestInquiryLookupRequest,
  InquiryCreateResponse,
  InquiryResponse,
} from ".././models";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 문의번호, 이메일, 비밀번호로 비회원 문의를 조회합니다.
 * @summary 비회원 문의 조회
 */
export type lookupGuestInquiryResponse200 = {
  data: InquiryResponse;
  status: 200;
};

export type lookupGuestInquiryResponse401 = {
  data: void;
  status: 401;
};

export type lookupGuestInquiryResponse404 = {
  data: void;
  status: 404;
};

export type lookupGuestInquiryResponseSuccess =
  lookupGuestInquiryResponse200 & {
    headers: Headers;
  };
export type lookupGuestInquiryResponseError = (
  | lookupGuestInquiryResponse401
  | lookupGuestInquiryResponse404
) & {
  headers: Headers;
};

export type lookupGuestInquiryResponse =
  | lookupGuestInquiryResponseSuccess
  | lookupGuestInquiryResponseError;

export const getLookupGuestInquiryUrl = () => {
  return `/api/v1/inquiries/lookup`;
};

export const lookupGuestInquiry = async (
  guestInquiryLookupRequest: GuestInquiryLookupRequest,
  options?: RequestInit,
): Promise<lookupGuestInquiryResponse> => {
  return customFetch<lookupGuestInquiryResponse>(getLookupGuestInquiryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(guestInquiryLookupRequest),
  });
};

export const getLookupGuestInquiryMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lookupGuestInquiry>>,
    TError,
    { data: GuestInquiryLookupRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof lookupGuestInquiry>>,
  TError,
  { data: GuestInquiryLookupRequest },
  TContext
> => {
  const mutationKey = ["lookupGuestInquiry"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lookupGuestInquiry>>,
    { data: GuestInquiryLookupRequest }
  > = (props) => {
    const { data } = props ?? {};

    return lookupGuestInquiry(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LookupGuestInquiryMutationResult = NonNullable<
  Awaited<ReturnType<typeof lookupGuestInquiry>>
>;
export type LookupGuestInquiryMutationBody = GuestInquiryLookupRequest;
export type LookupGuestInquiryMutationError = void;

/**
 * @summary 비회원 문의 조회
 */
export const useLookupGuestInquiry = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof lookupGuestInquiry>>,
      TError,
      { data: GuestInquiryLookupRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof lookupGuestInquiry>>,
  TError,
  { data: GuestInquiryLookupRequest },
  TContext
> => {
  return useMutation(
    getLookupGuestInquiryMutationOptions(options),
    queryClient,
  );
};
/**
 * 비회원이 문의를 작성합니다. 이메일, 이름, 비밀번호가 필수입니다.
 * @summary 비회원 문의 작성
 */
export type createGuestInquiryResponse201 = {
  data: InquiryCreateResponse;
  status: 201;
};

export type createGuestInquiryResponse400 = {
  data: void;
  status: 400;
};

export type createGuestInquiryResponseSuccess =
  createGuestInquiryResponse201 & {
    headers: Headers;
  };
export type createGuestInquiryResponseError = createGuestInquiryResponse400 & {
  headers: Headers;
};

export type createGuestInquiryResponse =
  | createGuestInquiryResponseSuccess
  | createGuestInquiryResponseError;

export const getCreateGuestInquiryUrl = () => {
  return `/api/v1/inquiries/guest`;
};

export const createGuestInquiry = async (
  createGuestInquiryRequest: CreateGuestInquiryRequest,
  options?: RequestInit,
): Promise<createGuestInquiryResponse> => {
  return customFetch<createGuestInquiryResponse>(getCreateGuestInquiryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createGuestInquiryRequest),
  });
};

export const getCreateGuestInquiryMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGuestInquiry>>,
    TError,
    { data: CreateGuestInquiryRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createGuestInquiry>>,
  TError,
  { data: CreateGuestInquiryRequest },
  TContext
> => {
  const mutationKey = ["createGuestInquiry"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createGuestInquiry>>,
    { data: CreateGuestInquiryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createGuestInquiry(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateGuestInquiryMutationResult = NonNullable<
  Awaited<ReturnType<typeof createGuestInquiry>>
>;
export type CreateGuestInquiryMutationBody = CreateGuestInquiryRequest;
export type CreateGuestInquiryMutationError = void;

/**
 * @summary 비회원 문의 작성
 */
export const useCreateGuestInquiry = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createGuestInquiry>>,
      TError,
      { data: CreateGuestInquiryRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createGuestInquiry>>,
  TError,
  { data: CreateGuestInquiryRequest },
  TContext
> => {
  return useMutation(
    getCreateGuestInquiryMutationOptions(options),
    queryClient,
  );
};
