/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeUserRoleRequest,
  ChangeUserStatusRequest,
  ForceWithdrawRequest,
  GetRoleHistoriesParams,
  GetUserListParams,
  PageUserRoleHistoryResponse,
  UserDetailResponse,
  UserListPageResponse
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 회원을 정지하거나 정지를 해제합니다. SUSPEND: 사유와 종료일 필수. LIFT: 활성 정지가 있어야 합니다.
 * @summary 회원 상태 변경 (정지/해제)
 */
export type changeUserStatusResponse204 = {
  data: void
  status: 204
}

export type changeUserStatusResponse400 = {
  data: void
  status: 400
}

export type changeUserStatusResponse401 = {
  data: void
  status: 401
}

export type changeUserStatusResponse403 = {
  data: void
  status: 403
}

export type changeUserStatusResponse404 = {
  data: void
  status: 404
}
    
export type changeUserStatusResponseSuccess = (changeUserStatusResponse204) & {
  headers: Headers;
};
export type changeUserStatusResponseError = (changeUserStatusResponse400 | changeUserStatusResponse401 | changeUserStatusResponse403 | changeUserStatusResponse404) & {
  headers: Headers;
};

export type changeUserStatusResponse = (changeUserStatusResponseSuccess | changeUserStatusResponseError)

export const getChangeUserStatusUrl = (userId: number,) => {


  

  return `/api/v1/admin/users/${userId}/status`
}

export const changeUserStatus = async (userId: number,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: RequestInit): Promise<changeUserStatusResponse> => {
  
  return customFetch<changeUserStatusResponse>(getChangeUserStatusUrl(userId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeUserStatusRequest,)
  }
);}




export const getChangeUserStatusMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUserStatus>>, TError,{userId: number;data: ChangeUserStatusRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeUserStatus>>, TError,{userId: number;data: ChangeUserStatusRequest}, TContext> => {

const mutationKey = ['changeUserStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeUserStatus>>, {userId: number;data: ChangeUserStatusRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  changeUserStatus(userId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeUserStatusMutationResult = NonNullable<Awaited<ReturnType<typeof changeUserStatus>>>
    export type ChangeUserStatusMutationBody = ChangeUserStatusRequest
    export type ChangeUserStatusMutationError = void

    /**
 * @summary 회원 상태 변경 (정지/해제)
 */
export const useChangeUserStatus = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUserStatus>>, TError,{userId: number;data: ChangeUserStatusRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeUserStatus>>,
        TError,
        {userId: number;data: ChangeUserStatusRequest},
        TContext
      > => {
      return useMutation(getChangeUserStatusMutationOptions(options), queryClient);
    }
    /**
 * 회원의 권한을 변경합니다.
 * @summary 회원 권한 변경
 */
export type changeUserRoleResponse204 = {
  data: void
  status: 204
}

export type changeUserRoleResponse400 = {
  data: void
  status: 400
}

export type changeUserRoleResponse401 = {
  data: void
  status: 401
}

export type changeUserRoleResponse403 = {
  data: void
  status: 403
}

export type changeUserRoleResponse404 = {
  data: void
  status: 404
}
    
export type changeUserRoleResponseSuccess = (changeUserRoleResponse204) & {
  headers: Headers;
};
export type changeUserRoleResponseError = (changeUserRoleResponse400 | changeUserRoleResponse401 | changeUserRoleResponse403 | changeUserRoleResponse404) & {
  headers: Headers;
};

export type changeUserRoleResponse = (changeUserRoleResponseSuccess | changeUserRoleResponseError)

export const getChangeUserRoleUrl = (userId: number,) => {


  

  return `/api/v1/admin/users/${userId}/role`
}

export const changeUserRole = async (userId: number,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: RequestInit): Promise<changeUserRoleResponse> => {
  
  return customFetch<changeUserRoleResponse>(getChangeUserRoleUrl(userId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeUserRoleRequest,)
  }
);}




export const getChangeUserRoleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUserRole>>, TError,{userId: number;data: ChangeUserRoleRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeUserRole>>, TError,{userId: number;data: ChangeUserRoleRequest}, TContext> => {

const mutationKey = ['changeUserRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeUserRole>>, {userId: number;data: ChangeUserRoleRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  changeUserRole(userId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof changeUserRole>>>
    export type ChangeUserRoleMutationBody = ChangeUserRoleRequest
    export type ChangeUserRoleMutationError = void

    /**
 * @summary 회원 권한 변경
 */
export const useChangeUserRole = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUserRole>>, TError,{userId: number;data: ChangeUserRoleRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeUserRole>>,
        TError,
        {userId: number;data: ChangeUserRoleRequest},
        TContext
      > => {
      return useMutation(getChangeUserRoleMutationOptions(options), queryClient);
    }
    /**
 * 회원 목록을 조회합니다. 검색어, 역할, 상태로 필터링 가능합니다.
 * @summary 회원 목록 조회
 */
export type getUserListResponse200 = {
  data: UserListPageResponse
  status: 200
}

export type getUserListResponse401 = {
  data: UserListPageResponse
  status: 401
}

export type getUserListResponse403 = {
  data: UserListPageResponse
  status: 403
}
    
export type getUserListResponseSuccess = (getUserListResponse200) & {
  headers: Headers;
};
export type getUserListResponseError = (getUserListResponse401 | getUserListResponse403) & {
  headers: Headers;
};

export type getUserListResponse = (getUserListResponseSuccess | getUserListResponseError)

export const getGetUserListUrl = (params?: GetUserListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/users?${stringifiedParams}` : `/api/v1/admin/users`
}

export const getUserList = async (params?: GetUserListParams, options?: RequestInit): Promise<getUserListResponse> => {
  
  return customFetch<getUserListResponse>(getGetUserListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserListQueryKey = (params?: GetUserListParams,) => {
    return [
    `/api/v1/admin/users`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserListQueryOptions = <TData = Awaited<ReturnType<typeof getUserList>>, TError = UserListPageResponse>(params?: GetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserList>>> = ({ signal }) => getUserList(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserListQueryResult = NonNullable<Awaited<ReturnType<typeof getUserList>>>
export type GetUserListQueryError = UserListPageResponse


export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = UserListPageResponse>(
 params: undefined |  GetUserListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserList>>,
          TError,
          Awaited<ReturnType<typeof getUserList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = UserListPageResponse>(
 params?: GetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserList>>,
          TError,
          Awaited<ReturnType<typeof getUserList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = UserListPageResponse>(
 params?: GetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 회원 목록 조회
 */

export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = UserListPageResponse>(
 params?: GetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 특정 회원의 상세 정보를 조회합니다.
 * @summary 회원 상세 조회
 */
export type getUserDetailResponse200 = {
  data: UserDetailResponse
  status: 200
}

export type getUserDetailResponse401 = {
  data: UserDetailResponse
  status: 401
}

export type getUserDetailResponse403 = {
  data: UserDetailResponse
  status: 403
}

export type getUserDetailResponse404 = {
  data: UserDetailResponse
  status: 404
}
    
export type getUserDetailResponseSuccess = (getUserDetailResponse200) & {
  headers: Headers;
};
export type getUserDetailResponseError = (getUserDetailResponse401 | getUserDetailResponse403 | getUserDetailResponse404) & {
  headers: Headers;
};

export type getUserDetailResponse = (getUserDetailResponseSuccess | getUserDetailResponseError)

export const getGetUserDetailUrl = (userId: number,) => {


  

  return `/api/v1/admin/users/${userId}`
}

export const getUserDetail = async (userId: number, options?: RequestInit): Promise<getUserDetailResponse> => {
  
  return customFetch<getUserDetailResponse>(getGetUserDetailUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserDetailQueryKey = (userId: number,) => {
    return [
    `/api/v1/admin/users/${userId}`
    ] as const;
    }

    
export const getGetUserDetailQueryOptions = <TData = Awaited<ReturnType<typeof getUserDetail>>, TError = UserDetailResponse>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserDetailQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserDetail>>> = ({ signal }) => getUserDetail(userId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getUserDetail>>>
export type GetUserDetailQueryError = UserDetailResponse


export function useGetUserDetail<TData = Awaited<ReturnType<typeof getUserDetail>>, TError = UserDetailResponse>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserDetail>>,
          TError,
          Awaited<ReturnType<typeof getUserDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserDetail<TData = Awaited<ReturnType<typeof getUserDetail>>, TError = UserDetailResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserDetail>>,
          TError,
          Awaited<ReturnType<typeof getUserDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserDetail<TData = Awaited<ReturnType<typeof getUserDetail>>, TError = UserDetailResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 회원 상세 조회
 */

export function useGetUserDetail<TData = Awaited<ReturnType<typeof getUserDetail>>, TError = UserDetailResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserDetailQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 관리자가 회원을 강제 탈퇴시킵니다. 사유 입력 필수.
 * @summary 회원 강제 탈퇴
 */
export type forceWithdrawUserResponse204 = {
  data: void
  status: 204
}

export type forceWithdrawUserResponse400 = {
  data: void
  status: 400
}

export type forceWithdrawUserResponse401 = {
  data: void
  status: 401
}

export type forceWithdrawUserResponse403 = {
  data: void
  status: 403
}

export type forceWithdrawUserResponse404 = {
  data: void
  status: 404
}
    
export type forceWithdrawUserResponseSuccess = (forceWithdrawUserResponse204) & {
  headers: Headers;
};
export type forceWithdrawUserResponseError = (forceWithdrawUserResponse400 | forceWithdrawUserResponse401 | forceWithdrawUserResponse403 | forceWithdrawUserResponse404) & {
  headers: Headers;
};

export type forceWithdrawUserResponse = (forceWithdrawUserResponseSuccess | forceWithdrawUserResponseError)

export const getForceWithdrawUserUrl = (userId: number,) => {


  

  return `/api/v1/admin/users/${userId}`
}

export const forceWithdrawUser = async (userId: number,
    forceWithdrawRequest: ForceWithdrawRequest, options?: RequestInit): Promise<forceWithdrawUserResponse> => {
  
  return customFetch<forceWithdrawUserResponse>(getForceWithdrawUserUrl(userId),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forceWithdrawRequest,)
  }
);}




export const getForceWithdrawUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceWithdrawUser>>, TError,{userId: number;data: ForceWithdrawRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof forceWithdrawUser>>, TError,{userId: number;data: ForceWithdrawRequest}, TContext> => {

const mutationKey = ['forceWithdrawUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forceWithdrawUser>>, {userId: number;data: ForceWithdrawRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  forceWithdrawUser(userId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ForceWithdrawUserMutationResult = NonNullable<Awaited<ReturnType<typeof forceWithdrawUser>>>
    export type ForceWithdrawUserMutationBody = ForceWithdrawRequest
    export type ForceWithdrawUserMutationError = void

    /**
 * @summary 회원 강제 탈퇴
 */
export const useForceWithdrawUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceWithdrawUser>>, TError,{userId: number;data: ForceWithdrawRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof forceWithdrawUser>>,
        TError,
        {userId: number;data: ForceWithdrawRequest},
        TContext
      > => {
      return useMutation(getForceWithdrawUserMutationOptions(options), queryClient);
    }
    /**
 * 권한 변경 이력을 조회합니다. 사용자, 역할, 변경자, 날짜 범위로 필터링 가능합니다.
 * @summary 권한 변경 이력 조회
 */
export type getRoleHistoriesResponse200 = {
  data: PageUserRoleHistoryResponse
  status: 200
}

export type getRoleHistoriesResponse400 = {
  data: PageUserRoleHistoryResponse
  status: 400
}

export type getRoleHistoriesResponse401 = {
  data: PageUserRoleHistoryResponse
  status: 401
}

export type getRoleHistoriesResponse403 = {
  data: PageUserRoleHistoryResponse
  status: 403
}
    
export type getRoleHistoriesResponseSuccess = (getRoleHistoriesResponse200) & {
  headers: Headers;
};
export type getRoleHistoriesResponseError = (getRoleHistoriesResponse400 | getRoleHistoriesResponse401 | getRoleHistoriesResponse403) & {
  headers: Headers;
};

export type getRoleHistoriesResponse = (getRoleHistoriesResponseSuccess | getRoleHistoriesResponseError)

export const getGetRoleHistoriesUrl = (params?: GetRoleHistoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/users/role-histories?${stringifiedParams}` : `/api/v1/admin/users/role-histories`
}

export const getRoleHistories = async (params?: GetRoleHistoriesParams, options?: RequestInit): Promise<getRoleHistoriesResponse> => {
  
  return customFetch<getRoleHistoriesResponse>(getGetRoleHistoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetRoleHistoriesQueryKey = (params?: GetRoleHistoriesParams,) => {
    return [
    `/api/v1/admin/users/role-histories`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetRoleHistoriesQueryOptions = <TData = Awaited<ReturnType<typeof getRoleHistories>>, TError = PageUserRoleHistoryResponse>(params?: GetRoleHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleHistories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRoleHistoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoleHistories>>> = ({ signal }) => getRoleHistories(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoleHistories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoleHistoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getRoleHistories>>>
export type GetRoleHistoriesQueryError = PageUserRoleHistoryResponse


export function useGetRoleHistories<TData = Awaited<ReturnType<typeof getRoleHistories>>, TError = PageUserRoleHistoryResponse>(
 params: undefined |  GetRoleHistoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleHistories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoleHistories>>,
          TError,
          Awaited<ReturnType<typeof getRoleHistories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoleHistories<TData = Awaited<ReturnType<typeof getRoleHistories>>, TError = PageUserRoleHistoryResponse>(
 params?: GetRoleHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleHistories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoleHistories>>,
          TError,
          Awaited<ReturnType<typeof getRoleHistories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoleHistories<TData = Awaited<ReturnType<typeof getRoleHistories>>, TError = PageUserRoleHistoryResponse>(
 params?: GetRoleHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleHistories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 권한 변경 이력 조회
 */

export function useGetRoleHistories<TData = Awaited<ReturnType<typeof getRoleHistories>>, TError = PageUserRoleHistoryResponse>(
 params?: GetRoleHistoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleHistories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRoleHistoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




