/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMyResponse200,
  GetMyResponse401,
  GetMyResponse404,
  SubmitResponse201,
  SubmitResponse400,
  SubmitResponse401,
  SubmitResponse403,
  SubmitResponse404,
  SubmitResponse409,
  SubmitResponseBody,
  UpdateMyResponse200,
  UpdateMyResponse400,
  UpdateMyResponse401,
  UpdateMyResponse404,
  UpdateMyResponseBody
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 본인이 제출한 응답을 조회합니다.
 * @summary 본인 응답 조회
 */
export type getMyResponseResponse200 = {
  data: GetMyResponse200
  status: 200
}

export type getMyResponseResponse401 = {
  data: GetMyResponse401
  status: 401
}

export type getMyResponseResponse404 = {
  data: GetMyResponse404
  status: 404
}
    
export type getMyResponseResponseSuccess = (getMyResponseResponse200) & {
  headers: Headers;
};
export type getMyResponseResponseError = (getMyResponseResponse401 | getMyResponseResponse404) & {
  headers: Headers;
};

export type getMyResponseResponse = (getMyResponseResponseSuccess | getMyResponseResponseError)

export const getGetMyResponseUrl = (surveyId: number,) => {


  

  return `/api/v1/surveys/${surveyId}/responses/me`
}

export const getMyResponse = async (surveyId: number, options?: RequestInit): Promise<getMyResponseResponse> => {
  
  return customFetch<getMyResponseResponse>(getGetMyResponseUrl(surveyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyResponseQueryKey = (surveyId: number,) => {
    return [
    `/api/v1/surveys/${surveyId}/responses/me`
    ] as const;
    }

    
export const getGetMyResponseQueryOptions = <TData = Awaited<ReturnType<typeof getMyResponse>>, TError = GetMyResponse401 | GetMyResponse404>(surveyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyResponse>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyResponseQueryKey(surveyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyResponse>>> = ({ signal }) => getMyResponse(surveyId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(surveyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyResponse>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyResponseQueryResult = NonNullable<Awaited<ReturnType<typeof getMyResponse>>>
export type GetMyResponseQueryError = GetMyResponse401 | GetMyResponse404


export function useGetMyResponse<TData = Awaited<ReturnType<typeof getMyResponse>>, TError = GetMyResponse401 | GetMyResponse404>(
 surveyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyResponse>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyResponse>>,
          TError,
          Awaited<ReturnType<typeof getMyResponse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyResponse<TData = Awaited<ReturnType<typeof getMyResponse>>, TError = GetMyResponse401 | GetMyResponse404>(
 surveyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyResponse>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyResponse>>,
          TError,
          Awaited<ReturnType<typeof getMyResponse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyResponse<TData = Awaited<ReturnType<typeof getMyResponse>>, TError = GetMyResponse401 | GetMyResponse404>(
 surveyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyResponse>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 본인 응답 조회
 */

export function useGetMyResponse<TData = Awaited<ReturnType<typeof getMyResponse>>, TError = GetMyResponse401 | GetMyResponse404>(
 surveyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyResponse>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyResponseQueryOptions(surveyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 본인이 제출한 응답을 수정합니다. 설문이 OPEN 상태에서만 가능합니다.
 * @summary 본인 응답 수정
 */
export type updateMyResponseResponse200 = {
  data: UpdateMyResponse200
  status: 200
}

export type updateMyResponseResponse400 = {
  data: UpdateMyResponse400
  status: 400
}

export type updateMyResponseResponse401 = {
  data: UpdateMyResponse401
  status: 401
}

export type updateMyResponseResponse404 = {
  data: UpdateMyResponse404
  status: 404
}
    
export type updateMyResponseResponseSuccess = (updateMyResponseResponse200) & {
  headers: Headers;
};
export type updateMyResponseResponseError = (updateMyResponseResponse400 | updateMyResponseResponse401 | updateMyResponseResponse404) & {
  headers: Headers;
};

export type updateMyResponseResponse = (updateMyResponseResponseSuccess | updateMyResponseResponseError)

export const getUpdateMyResponseUrl = (surveyId: number,) => {


  

  return `/api/v1/surveys/${surveyId}/responses/me`
}

export const updateMyResponse = async (surveyId: number,
    updateMyResponseBody: UpdateMyResponseBody, options?: RequestInit): Promise<updateMyResponseResponse> => {
  
  return customFetch<updateMyResponseResponse>(getUpdateMyResponseUrl(surveyId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMyResponseBody,)
  }
);}




export const getUpdateMyResponseMutationOptions = <TError = UpdateMyResponse400 | UpdateMyResponse401 | UpdateMyResponse404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyResponse>>, TError,{surveyId: number;data: UpdateMyResponseBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMyResponse>>, TError,{surveyId: number;data: UpdateMyResponseBody}, TContext> => {

const mutationKey = ['updateMyResponse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMyResponse>>, {surveyId: number;data: UpdateMyResponseBody}> = (props) => {
          const {surveyId,data} = props ?? {};

          return  updateMyResponse(surveyId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMyResponseMutationResult = NonNullable<Awaited<ReturnType<typeof updateMyResponse>>>
    export type UpdateMyResponseMutationBody = UpdateMyResponseBody
    export type UpdateMyResponseMutationError = UpdateMyResponse400 | UpdateMyResponse401 | UpdateMyResponse404

    /**
 * @summary 본인 응답 수정
 */
export const useUpdateMyResponse = <TError = UpdateMyResponse400 | UpdateMyResponse401 | UpdateMyResponse404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyResponse>>, TError,{surveyId: number;data: UpdateMyResponseBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMyResponse>>,
        TError,
        {surveyId: number;data: UpdateMyResponseBody},
        TContext
      > => {
      return useMutation(getUpdateMyResponseMutationOptions(options), queryClient);
    }
    /**
 * 회원이 설문에 응답을 제출합니다. 설문당 1회만 가능합니다.
 * @summary 설문 응답 제출
 */
export type submitResponseResponse201 = {
  data: SubmitResponse201
  status: 201
}

export type submitResponseResponse400 = {
  data: SubmitResponse400
  status: 400
}

export type submitResponseResponse401 = {
  data: SubmitResponse401
  status: 401
}

export type submitResponseResponse403 = {
  data: SubmitResponse403
  status: 403
}

export type submitResponseResponse404 = {
  data: SubmitResponse404
  status: 404
}

export type submitResponseResponse409 = {
  data: SubmitResponse409
  status: 409
}
    
export type submitResponseResponseSuccess = (submitResponseResponse201) & {
  headers: Headers;
};
export type submitResponseResponseError = (submitResponseResponse400 | submitResponseResponse401 | submitResponseResponse403 | submitResponseResponse404 | submitResponseResponse409) & {
  headers: Headers;
};

export type submitResponseResponse = (submitResponseResponseSuccess | submitResponseResponseError)

export const getSubmitResponseUrl = (surveyId: number,) => {


  

  return `/api/v1/surveys/${surveyId}/responses`
}

export const submitResponse = async (surveyId: number,
    submitResponseBody: SubmitResponseBody, options?: RequestInit): Promise<submitResponseResponse> => {
  
  return customFetch<submitResponseResponse>(getSubmitResponseUrl(surveyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submitResponseBody,)
  }
);}




export const getSubmitResponseMutationOptions = <TError = SubmitResponse400 | SubmitResponse401 | SubmitResponse403 | SubmitResponse404 | SubmitResponse409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitResponse>>, TError,{surveyId: number;data: SubmitResponseBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitResponse>>, TError,{surveyId: number;data: SubmitResponseBody}, TContext> => {

const mutationKey = ['submitResponse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitResponse>>, {surveyId: number;data: SubmitResponseBody}> = (props) => {
          const {surveyId,data} = props ?? {};

          return  submitResponse(surveyId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitResponseMutationResult = NonNullable<Awaited<ReturnType<typeof submitResponse>>>
    export type SubmitResponseMutationBody = SubmitResponseBody
    export type SubmitResponseMutationError = SubmitResponse400 | SubmitResponse401 | SubmitResponse403 | SubmitResponse404 | SubmitResponse409

    /**
 * @summary 설문 응답 제출
 */
export const useSubmitResponse = <TError = SubmitResponse400 | SubmitResponse401 | SubmitResponse403 | SubmitResponse404 | SubmitResponse409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitResponse>>, TError,{surveyId: number;data: SubmitResponseBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitResponse>>,
        TError,
        {surveyId: number;data: SubmitResponseBody},
        TContext
      > => {
      return useMutation(getSubmitResponseMutationOptions(options), queryClient);
    }
    