/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetMemberListParams,
  SemesterMemberListResponse,
  SemesterSummaryResponse,
} from ".././models";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 멤버십 기록이 존재하는 학기 목록을 회원 수와 함께 최신순으로 조회합니다.
 * @summary 학기 목록 조회
 */
export type getSemesterListResponse200 = {
  data: SemesterSummaryResponse[];
  status: 200;
};

export type getSemesterListResponse401 = {
  data: void;
  status: 401;
};

export type getSemesterListResponse403 = {
  data: void;
  status: 403;
};

export type getSemesterListResponseSuccess = getSemesterListResponse200 & {
  headers: Headers;
};
export type getSemesterListResponseError = (
  | getSemesterListResponse401
  | getSemesterListResponse403
) & {
  headers: Headers;
};

export type getSemesterListResponse =
  | getSemesterListResponseSuccess
  | getSemesterListResponseError;

export const getGetSemesterListUrl = () => {
  return `/api/v1/semesters`;
};

export const getSemesterList = async (
  options?: RequestInit,
): Promise<getSemesterListResponse> => {
  return customFetch<getSemesterListResponse>(getGetSemesterListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSemesterListQueryKey = () => {
  return [`/api/v1/semesters`] as const;
};

export const getGetSemesterListQueryOptions = <
  TData = Awaited<ReturnType<typeof getSemesterList>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getSemesterList>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSemesterListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSemesterList>>> = ({
    signal,
  }) => getSemesterList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSemesterList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSemesterListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSemesterList>>
>;
export type GetSemesterListQueryError = void;

export function useGetSemesterList<
  TData = Awaited<ReturnType<typeof getSemesterList>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSemesterList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSemesterList>>,
          TError,
          Awaited<ReturnType<typeof getSemesterList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSemesterList<
  TData = Awaited<ReturnType<typeof getSemesterList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSemesterList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSemesterList>>,
          TError,
          Awaited<ReturnType<typeof getSemesterList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSemesterList<
  TData = Awaited<ReturnType<typeof getSemesterList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSemesterList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 학기 목록 조회
 */

export function useGetSemesterList<
  TData = Awaited<ReturnType<typeof getSemesterList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSemesterList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSemesterListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 특정 학기의 회원 명단을 조회합니다. 탈퇴 회원도 포함됩니다.
 * @summary 학기별 회원 명단 조회
 */
export type getMemberListResponse200 = {
  data: SemesterMemberListResponse[];
  status: 200;
};

export type getMemberListResponse400 = {
  data: void;
  status: 400;
};

export type getMemberListResponse401 = {
  data: void;
  status: 401;
};

export type getMemberListResponse403 = {
  data: void;
  status: 403;
};

export type getMemberListResponseSuccess = getMemberListResponse200 & {
  headers: Headers;
};
export type getMemberListResponseError = (
  | getMemberListResponse400
  | getMemberListResponse401
  | getMemberListResponse403
) & {
  headers: Headers;
};

export type getMemberListResponse =
  | getMemberListResponseSuccess
  | getMemberListResponseError;

export const getGetMemberListUrl = (
  year: number,
  semester: number,
  params?: GetMemberListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/semesters/${year}/${semester}/members?${stringifiedParams}`
    : `/api/v1/semesters/${year}/${semester}/members`;
};

export const getMemberList = async (
  year: number,
  semester: number,
  params?: GetMemberListParams,
  options?: RequestInit,
): Promise<getMemberListResponse> => {
  return customFetch<getMemberListResponse>(
    getGetMemberListUrl(year, semester, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMemberListQueryKey = (
  year: number,
  semester: number,
  params?: GetMemberListParams,
) => {
  return [
    `/api/v1/semesters/${year}/${semester}/members`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMemberListQueryOptions = <
  TData = Awaited<ReturnType<typeof getMemberList>>,
  TError = void,
>(
  year: number,
  semester: number,
  params?: GetMemberListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMemberList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMemberListQueryKey(year, semester, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemberList>>> = ({
    signal,
  }) => getMemberList(year, semester, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(year && semester),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMemberList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMemberListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMemberList>>
>;
export type GetMemberListQueryError = void;

export function useGetMemberList<
  TData = Awaited<ReturnType<typeof getMemberList>>,
  TError = void,
>(
  year: number,
  semester: number,
  params: undefined | GetMemberListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMemberList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemberList>>,
          TError,
          Awaited<ReturnType<typeof getMemberList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberList<
  TData = Awaited<ReturnType<typeof getMemberList>>,
  TError = void,
>(
  year: number,
  semester: number,
  params?: GetMemberListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMemberList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemberList>>,
          TError,
          Awaited<ReturnType<typeof getMemberList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberList<
  TData = Awaited<ReturnType<typeof getMemberList>>,
  TError = void,
>(
  year: number,
  semester: number,
  params?: GetMemberListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMemberList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 학기별 회원 명단 조회
 */

export function useGetMemberList<
  TData = Awaited<ReturnType<typeof getMemberList>>,
  TError = void,
>(
  year: number,
  semester: number,
  params?: GetMemberListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMemberList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMemberListQueryOptions(
    year,
    semester,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
