/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePostRequest,
  GetPostListParams,
  GetPostViewHistoryParams,
  PostCreateResponse,
  PostDetailResponse,
  PostListPageResponse,
  PostUpdateResponse,
  PostViewHistoryPageResponse,
  PostViewStatsResponse,
  UpdatePostRequest
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 게시글의 상세 정보를 조회합니다. 조회 시 조회수가 1 증가합니다.
 * @summary 게시글 상세 조회
 */
export type getPostDetailResponse200 = {
  data: PostDetailResponse
  status: 200
}

export type getPostDetailResponse401 = {
  data: PostDetailResponse
  status: 401
}

export type getPostDetailResponse403 = {
  data: PostDetailResponse
  status: 403
}

export type getPostDetailResponse404 = {
  data: PostDetailResponse
  status: 404
}
    
export type getPostDetailResponseSuccess = (getPostDetailResponse200) & {
  headers: Headers;
};
export type getPostDetailResponseError = (getPostDetailResponse401 | getPostDetailResponse403 | getPostDetailResponse404) & {
  headers: Headers;
};

export type getPostDetailResponse = (getPostDetailResponseSuccess | getPostDetailResponseError)

export const getGetPostDetailUrl = (boardCode: string,
    postId: number,) => {


  

  return `/api/v1/boards/${boardCode}/posts/${postId}`
}

export const getPostDetail = async (boardCode: string,
    postId: number, options?: RequestInit): Promise<getPostDetailResponse> => {
  
  return customFetch<getPostDetailResponse>(getGetPostDetailUrl(boardCode,postId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPostDetailQueryKey = (boardCode: string,
    postId: number,) => {
    return [
    `/api/v1/boards/${boardCode}/posts/${postId}`
    ] as const;
    }

    
export const getGetPostDetailQueryOptions = <TData = Awaited<ReturnType<typeof getPostDetail>>, TError = PostDetailResponse>(boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostDetailQueryKey(boardCode,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostDetail>>> = ({ signal }) => getPostDetail(boardCode,postId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(boardCode && postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getPostDetail>>>
export type GetPostDetailQueryError = PostDetailResponse


export function useGetPostDetail<TData = Awaited<ReturnType<typeof getPostDetail>>, TError = PostDetailResponse>(
 boardCode: string,
    postId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostDetail>>,
          TError,
          Awaited<ReturnType<typeof getPostDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostDetail<TData = Awaited<ReturnType<typeof getPostDetail>>, TError = PostDetailResponse>(
 boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostDetail>>,
          TError,
          Awaited<ReturnType<typeof getPostDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostDetail<TData = Awaited<ReturnType<typeof getPostDetail>>, TError = PostDetailResponse>(
 boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 상세 조회
 */

export function useGetPostDetail<TData = Awaited<ReturnType<typeof getPostDetail>>, TError = PostDetailResponse>(
 boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostDetailQueryOptions(boardCode,postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 게시글을 수정합니다. 작성자 본인 또는 관리자만 수정 가능합니다.
 * @summary 게시글 수정
 */
export type updatePostResponse200 = {
  data: PostUpdateResponse
  status: 200
}

export type updatePostResponse400 = {
  data: PostUpdateResponse
  status: 400
}

export type updatePostResponse401 = {
  data: PostUpdateResponse
  status: 401
}

export type updatePostResponse403 = {
  data: PostUpdateResponse
  status: 403
}

export type updatePostResponse404 = {
  data: PostUpdateResponse
  status: 404
}
    
export type updatePostResponseSuccess = (updatePostResponse200) & {
  headers: Headers;
};
export type updatePostResponseError = (updatePostResponse400 | updatePostResponse401 | updatePostResponse403 | updatePostResponse404) & {
  headers: Headers;
};

export type updatePostResponse = (updatePostResponseSuccess | updatePostResponseError)

export const getUpdatePostUrl = (boardCode: string,
    postId: number,) => {


  

  return `/api/v1/boards/${boardCode}/posts/${postId}`
}

export const updatePost = async (boardCode: string,
    postId: number,
    updatePostRequest: UpdatePostRequest, options?: RequestInit): Promise<updatePostResponse> => {
  
  return customFetch<updatePostResponse>(getUpdatePostUrl(boardCode,postId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePostRequest,)
  }
);}




export const getUpdatePostMutationOptions = <TError = PostUpdateResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{boardCode: string;postId: number;data: UpdatePostRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{boardCode: string;postId: number;data: UpdatePostRequest}, TContext> => {

const mutationKey = ['updatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePost>>, {boardCode: string;postId: number;data: UpdatePostRequest}> = (props) => {
          const {boardCode,postId,data} = props ?? {};

          return  updatePost(boardCode,postId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePost>>>
    export type UpdatePostMutationBody = UpdatePostRequest
    export type UpdatePostMutationError = PostUpdateResponse

    /**
 * @summary 게시글 수정
 */
export const useUpdatePost = <TError = PostUpdateResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{boardCode: string;postId: number;data: UpdatePostRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePost>>,
        TError,
        {boardCode: string;postId: number;data: UpdatePostRequest},
        TContext
      > => {
      return useMutation(getUpdatePostMutationOptions(options), queryClient);
    }
    /**
 * 게시글을 삭제합니다. 작성자 본인 또는 운영자 이상 권한을 가진 사용자만 삭제 가능합니다.
 * @summary 게시글 삭제
 */
export type deletePostResponse204 = {
  data: void
  status: 204
}

export type deletePostResponse401 = {
  data: void
  status: 401
}

export type deletePostResponse403 = {
  data: void
  status: 403
}

export type deletePostResponse404 = {
  data: void
  status: 404
}
    
export type deletePostResponseSuccess = (deletePostResponse204) & {
  headers: Headers;
};
export type deletePostResponseError = (deletePostResponse401 | deletePostResponse403 | deletePostResponse404) & {
  headers: Headers;
};

export type deletePostResponse = (deletePostResponseSuccess | deletePostResponseError)

export const getDeletePostUrl = (boardCode: string,
    postId: number,) => {


  

  return `/api/v1/boards/${boardCode}/posts/${postId}`
}

export const deletePost = async (boardCode: string,
    postId: number, options?: RequestInit): Promise<deletePostResponse> => {
  
  return customFetch<deletePostResponse>(getDeletePostUrl(boardCode,postId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeletePostMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{boardCode: string;postId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{boardCode: string;postId: number}, TContext> => {

const mutationKey = ['deletePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePost>>, {boardCode: string;postId: number}> = (props) => {
          const {boardCode,postId} = props ?? {};

          return  deletePost(boardCode,postId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePost>>>
    
    export type DeletePostMutationError = void

    /**
 * @summary 게시글 삭제
 */
export const useDeletePost = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{boardCode: string;postId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePost>>,
        TError,
        {boardCode: string;postId: number},
        TContext
      > => {
      return useMutation(getDeletePostMutationOptions(options), queryClient);
    }
    /**
 * 게시판의 게시글 목록을 페이징하여 조회합니다. 키워드 검색 및 질문글 필터링을 지원합니다.
 * @summary 게시글 목록 조회
 */
export type getPostListResponse200 = {
  data: PostListPageResponse
  status: 200
}

export type getPostListResponse401 = {
  data: PostListPageResponse
  status: 401
}

export type getPostListResponse403 = {
  data: PostListPageResponse
  status: 403
}

export type getPostListResponse404 = {
  data: PostListPageResponse
  status: 404
}
    
export type getPostListResponseSuccess = (getPostListResponse200) & {
  headers: Headers;
};
export type getPostListResponseError = (getPostListResponse401 | getPostListResponse403 | getPostListResponse404) & {
  headers: Headers;
};

export type getPostListResponse = (getPostListResponseSuccess | getPostListResponseError)

export const getGetPostListUrl = (boardCode: string,
    params?: GetPostListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/boards/${boardCode}/posts?${stringifiedParams}` : `/api/v1/boards/${boardCode}/posts`
}

export const getPostList = async (boardCode: string,
    params?: GetPostListParams, options?: RequestInit): Promise<getPostListResponse> => {
  
  return customFetch<getPostListResponse>(getGetPostListUrl(boardCode,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPostListQueryKey = (boardCode: string,
    params?: GetPostListParams,) => {
    return [
    `/api/v1/boards/${boardCode}/posts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetPostListQueryOptions = <TData = Awaited<ReturnType<typeof getPostList>>, TError = PostListPageResponse>(boardCode: string,
    params?: GetPostListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostListQueryKey(boardCode,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostList>>> = ({ signal }) => getPostList(boardCode,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(boardCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostListQueryResult = NonNullable<Awaited<ReturnType<typeof getPostList>>>
export type GetPostListQueryError = PostListPageResponse


export function useGetPostList<TData = Awaited<ReturnType<typeof getPostList>>, TError = PostListPageResponse>(
 boardCode: string,
    params: undefined |  GetPostListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostList>>,
          TError,
          Awaited<ReturnType<typeof getPostList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostList<TData = Awaited<ReturnType<typeof getPostList>>, TError = PostListPageResponse>(
 boardCode: string,
    params?: GetPostListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostList>>,
          TError,
          Awaited<ReturnType<typeof getPostList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostList<TData = Awaited<ReturnType<typeof getPostList>>, TError = PostListPageResponse>(
 boardCode: string,
    params?: GetPostListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 목록 조회
 */

export function useGetPostList<TData = Awaited<ReturnType<typeof getPostList>>, TError = PostListPageResponse>(
 boardCode: string,
    params?: GetPostListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostListQueryOptions(boardCode,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 게시판에 새 게시글을 작성합니다
 * @summary 게시글 작성
 */
export type createPostResponse201 = {
  data: PostCreateResponse
  status: 201
}

export type createPostResponse400 = {
  data: PostCreateResponse
  status: 400
}

export type createPostResponse401 = {
  data: PostCreateResponse
  status: 401
}

export type createPostResponse403 = {
  data: PostCreateResponse
  status: 403
}

export type createPostResponse404 = {
  data: PostCreateResponse
  status: 404
}

export type createPostResponse429 = {
  data: PostCreateResponse
  status: 429
}
    
export type createPostResponseSuccess = (createPostResponse201) & {
  headers: Headers;
};
export type createPostResponseError = (createPostResponse400 | createPostResponse401 | createPostResponse403 | createPostResponse404 | createPostResponse429) & {
  headers: Headers;
};

export type createPostResponse = (createPostResponseSuccess | createPostResponseError)

export const getCreatePostUrl = (boardCode: string,) => {


  

  return `/api/v1/boards/${boardCode}/posts`
}

export const createPost = async (boardCode: string,
    createPostRequest: CreatePostRequest, options?: RequestInit): Promise<createPostResponse> => {
  
  return customFetch<createPostResponse>(getCreatePostUrl(boardCode),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPostRequest,)
  }
);}




export const getCreatePostMutationOptions = <TError = PostCreateResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{boardCode: string;data: CreatePostRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{boardCode: string;data: CreatePostRequest}, TContext> => {

const mutationKey = ['createPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPost>>, {boardCode: string;data: CreatePostRequest}> = (props) => {
          const {boardCode,data} = props ?? {};

          return  createPost(boardCode,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createPost>>>
    export type CreatePostMutationBody = CreatePostRequest
    export type CreatePostMutationError = PostCreateResponse

    /**
 * @summary 게시글 작성
 */
export const useCreatePost = <TError = PostCreateResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{boardCode: string;data: CreatePostRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPost>>,
        TError,
        {boardCode: string;data: CreatePostRequest},
        TContext
      > => {
      return useMutation(getCreatePostMutationOptions(options), queryClient);
    }
    /**
 * 게시글의 조회 통계를 조회합니다. OPERATOR 이상만 조회 가능합니다.
 * @summary 게시글 조회 통계
 */
export type getPostViewStatsResponse200 = {
  data: PostViewStatsResponse
  status: 200
}

export type getPostViewStatsResponse401 = {
  data: PostViewStatsResponse
  status: 401
}

export type getPostViewStatsResponse403 = {
  data: PostViewStatsResponse
  status: 403
}

export type getPostViewStatsResponse404 = {
  data: PostViewStatsResponse
  status: 404
}
    
export type getPostViewStatsResponseSuccess = (getPostViewStatsResponse200) & {
  headers: Headers;
};
export type getPostViewStatsResponseError = (getPostViewStatsResponse401 | getPostViewStatsResponse403 | getPostViewStatsResponse404) & {
  headers: Headers;
};

export type getPostViewStatsResponse = (getPostViewStatsResponseSuccess | getPostViewStatsResponseError)

export const getGetPostViewStatsUrl = (boardCode: string,
    postId: number,) => {


  

  return `/api/v1/boards/${boardCode}/posts/${postId}/view-stats`
}

export const getPostViewStats = async (boardCode: string,
    postId: number, options?: RequestInit): Promise<getPostViewStatsResponse> => {
  
  return customFetch<getPostViewStatsResponse>(getGetPostViewStatsUrl(boardCode,postId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPostViewStatsQueryKey = (boardCode: string,
    postId: number,) => {
    return [
    `/api/v1/boards/${boardCode}/posts/${postId}/view-stats`
    ] as const;
    }

    
export const getGetPostViewStatsQueryOptions = <TData = Awaited<ReturnType<typeof getPostViewStats>>, TError = PostViewStatsResponse>(boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostViewStatsQueryKey(boardCode,postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostViewStats>>> = ({ signal }) => getPostViewStats(boardCode,postId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(boardCode && postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostViewStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostViewStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getPostViewStats>>>
export type GetPostViewStatsQueryError = PostViewStatsResponse


export function useGetPostViewStats<TData = Awaited<ReturnType<typeof getPostViewStats>>, TError = PostViewStatsResponse>(
 boardCode: string,
    postId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostViewStats>>,
          TError,
          Awaited<ReturnType<typeof getPostViewStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostViewStats<TData = Awaited<ReturnType<typeof getPostViewStats>>, TError = PostViewStatsResponse>(
 boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostViewStats>>,
          TError,
          Awaited<ReturnType<typeof getPostViewStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostViewStats<TData = Awaited<ReturnType<typeof getPostViewStats>>, TError = PostViewStatsResponse>(
 boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 조회 통계
 */

export function useGetPostViewStats<TData = Awaited<ReturnType<typeof getPostViewStats>>, TError = PostViewStatsResponse>(
 boardCode: string,
    postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostViewStatsQueryOptions(boardCode,postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 게시글의 조회 기록을 페이징하여 조회합니다. OPERATOR 이상만 조회 가능합니다.
 * @summary 게시글 조회 기록 목록
 */
export type getPostViewHistoryResponse200 = {
  data: PostViewHistoryPageResponse
  status: 200
}

export type getPostViewHistoryResponse401 = {
  data: PostViewHistoryPageResponse
  status: 401
}

export type getPostViewHistoryResponse403 = {
  data: PostViewHistoryPageResponse
  status: 403
}

export type getPostViewHistoryResponse404 = {
  data: PostViewHistoryPageResponse
  status: 404
}
    
export type getPostViewHistoryResponseSuccess = (getPostViewHistoryResponse200) & {
  headers: Headers;
};
export type getPostViewHistoryResponseError = (getPostViewHistoryResponse401 | getPostViewHistoryResponse403 | getPostViewHistoryResponse404) & {
  headers: Headers;
};

export type getPostViewHistoryResponse = (getPostViewHistoryResponseSuccess | getPostViewHistoryResponseError)

export const getGetPostViewHistoryUrl = (boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/boards/${boardCode}/posts/${postId}/view-history?${stringifiedParams}` : `/api/v1/boards/${boardCode}/posts/${postId}/view-history`
}

export const getPostViewHistory = async (boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams, options?: RequestInit): Promise<getPostViewHistoryResponse> => {
  
  return customFetch<getPostViewHistoryResponse>(getGetPostViewHistoryUrl(boardCode,postId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPostViewHistoryQueryKey = (boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams,) => {
    return [
    `/api/v1/boards/${boardCode}/posts/${postId}/view-history`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetPostViewHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getPostViewHistory>>, TError = PostViewHistoryPageResponse>(boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewHistory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostViewHistoryQueryKey(boardCode,postId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostViewHistory>>> = ({ signal }) => getPostViewHistory(boardCode,postId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(boardCode && postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostViewHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostViewHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getPostViewHistory>>>
export type GetPostViewHistoryQueryError = PostViewHistoryPageResponse


export function useGetPostViewHistory<TData = Awaited<ReturnType<typeof getPostViewHistory>>, TError = PostViewHistoryPageResponse>(
 boardCode: string,
    postId: number,
    params: undefined |  GetPostViewHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostViewHistory>>,
          TError,
          Awaited<ReturnType<typeof getPostViewHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostViewHistory<TData = Awaited<ReturnType<typeof getPostViewHistory>>, TError = PostViewHistoryPageResponse>(
 boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostViewHistory>>,
          TError,
          Awaited<ReturnType<typeof getPostViewHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostViewHistory<TData = Awaited<ReturnType<typeof getPostViewHistory>>, TError = PostViewHistoryPageResponse>(
 boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewHistory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 게시글 조회 기록 목록
 */

export function useGetPostViewHistory<TData = Awaited<ReturnType<typeof getPostViewHistory>>, TError = PostViewHistoryPageResponse>(
 boardCode: string,
    postId: number,
    params?: GetPostViewHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostViewHistory>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostViewHistoryQueryOptions(boardCode,postId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




