/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommentListResponse,
  CommentResponse,
  CreateCommentRequest
} from '.././models';

import { customFetch } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 게시글의 댓글 목록을 계층 구조로 조회합니다. 등록순(오래된 순)으로 정렬됩니다.
 * @summary 댓글 목록 조회
 */
export type getCommentsResponse200 = {
  data: CommentListResponse
  status: 200
}

export type getCommentsResponse404 = {
  data: CommentListResponse
  status: 404
}
    
export type getCommentsResponseSuccess = (getCommentsResponse200) & {
  headers: Headers;
};
export type getCommentsResponseError = (getCommentsResponse404) & {
  headers: Headers;
};

export type getCommentsResponse = (getCommentsResponseSuccess | getCommentsResponseError)

export const getGetCommentsUrl = (postId: number,) => {


  

  return `/api/v1/posts/${postId}/comments`
}

export const getComments = async (postId: number, options?: RequestInit): Promise<getCommentsResponse> => {
  
  return customFetch<getCommentsResponse>(getGetCommentsUrl(postId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCommentsQueryKey = (postId: number,) => {
    return [
    `/api/v1/posts/${postId}/comments`
    ] as const;
    }

    
export const getGetCommentsQueryOptions = <TData = Awaited<ReturnType<typeof getComments>>, TError = CommentListResponse>(postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommentsQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComments>>> = ({ signal }) => getComments(postId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof getComments>>>
export type GetCommentsQueryError = CommentListResponse


export function useGetComments<TData = Awaited<ReturnType<typeof getComments>>, TError = CommentListResponse>(
 postId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments>>,
          TError,
          Awaited<ReturnType<typeof getComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComments<TData = Awaited<ReturnType<typeof getComments>>, TError = CommentListResponse>(
 postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments>>,
          TError,
          Awaited<ReturnType<typeof getComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComments<TData = Awaited<ReturnType<typeof getComments>>, TError = CommentListResponse>(
 postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 댓글 목록 조회
 */

export function useGetComments<TData = Awaited<ReturnType<typeof getComments>>, TError = CommentListResponse>(
 postId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommentsQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 게시글에 댓글을 작성합니다. 정회원 이상만 작성 가능합니다.
 * @summary 댓글 작성
 */
export type createCommentResponse201 = {
  data: CommentResponse
  status: 201
}

export type createCommentResponse400 = {
  data: CommentResponse
  status: 400
}

export type createCommentResponse401 = {
  data: CommentResponse
  status: 401
}

export type createCommentResponse403 = {
  data: CommentResponse
  status: 403
}

export type createCommentResponse404 = {
  data: CommentResponse
  status: 404
}
    
export type createCommentResponseSuccess = (createCommentResponse201) & {
  headers: Headers;
};
export type createCommentResponseError = (createCommentResponse400 | createCommentResponse401 | createCommentResponse403 | createCommentResponse404) & {
  headers: Headers;
};

export type createCommentResponse = (createCommentResponseSuccess | createCommentResponseError)

export const getCreateCommentUrl = (postId: number,) => {


  

  return `/api/v1/posts/${postId}/comments`
}

export const createComment = async (postId: number,
    createCommentRequest: CreateCommentRequest, options?: RequestInit): Promise<createCommentResponse> => {
  
  return customFetch<createCommentResponse>(getCreateCommentUrl(postId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCommentRequest,)
  }
);}




export const getCreateCommentMutationOptions = <TError = CommentResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{postId: number;data: CreateCommentRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{postId: number;data: CreateCommentRequest}, TContext> => {

const mutationKey = ['createComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createComment>>, {postId: number;data: CreateCommentRequest}> = (props) => {
          const {postId,data} = props ?? {};

          return  createComment(postId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createComment>>>
    export type CreateCommentMutationBody = CreateCommentRequest
    export type CreateCommentMutationError = CommentResponse

    /**
 * @summary 댓글 작성
 */
export const useCreateComment = <TError = CommentResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{postId: number;data: CreateCommentRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createComment>>,
        TError,
        {postId: number;data: CreateCommentRequest},
        TContext
      > => {
      return useMutation(getCreateCommentMutationOptions(options), queryClient);
    }
    /**
 * 댓글에 대댓글을 작성합니다. 정회원 이상만 작성 가능하며, 대댓글에는 답글을 달 수 없습니다 (1단계까지만 허용).
 * @summary 대댓글 작성
 */
export type createReply1Response201 = {
  data: CommentResponse
  status: 201
}

export type createReply1Response400 = {
  data: CommentResponse
  status: 400
}

export type createReply1Response401 = {
  data: CommentResponse
  status: 401
}

export type createReply1Response403 = {
  data: CommentResponse
  status: 403
}

export type createReply1Response404 = {
  data: CommentResponse
  status: 404
}
    
export type createReply1ResponseSuccess = (createReply1Response201) & {
  headers: Headers;
};
export type createReply1ResponseError = (createReply1Response400 | createReply1Response401 | createReply1Response403 | createReply1Response404) & {
  headers: Headers;
};

export type createReply1Response = (createReply1ResponseSuccess | createReply1ResponseError)

export const getCreateReply1Url = (postId: number,
    commentId: number,) => {


  

  return `/api/v1/posts/${postId}/comments/${commentId}/replies`
}

export const createReply1 = async (postId: number,
    commentId: number,
    createCommentRequest: CreateCommentRequest, options?: RequestInit): Promise<createReply1Response> => {
  
  return customFetch<createReply1Response>(getCreateReply1Url(postId,commentId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCommentRequest,)
  }
);}




export const getCreateReply1MutationOptions = <TError = CommentResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReply1>>, TError,{postId: number;commentId: number;data: CreateCommentRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createReply1>>, TError,{postId: number;commentId: number;data: CreateCommentRequest}, TContext> => {

const mutationKey = ['createReply1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReply1>>, {postId: number;commentId: number;data: CreateCommentRequest}> = (props) => {
          const {postId,commentId,data} = props ?? {};

          return  createReply1(postId,commentId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReply1MutationResult = NonNullable<Awaited<ReturnType<typeof createReply1>>>
    export type CreateReply1MutationBody = CreateCommentRequest
    export type CreateReply1MutationError = CommentResponse

    /**
 * @summary 대댓글 작성
 */
export const useCreateReply1 = <TError = CommentResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReply1>>, TError,{postId: number;commentId: number;data: CreateCommentRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReply1>>,
        TError,
        {postId: number;commentId: number;data: CreateCommentRequest},
        TContext
      > => {
      return useMutation(getCreateReply1MutationOptions(options), queryClient);
    }
    /**
 * 댓글을 삭제합니다. 작성자 본인 또는 운영자 이상 권한을 가진 사용자만 삭제 가능합니다. Soft Delete로 처리되며, 삭제된 댓글은 '삭제된 댓글입니다'로 표시됩니다.
 * @summary 댓글 삭제
 */
export type deleteCommentResponse204 = {
  data: void
  status: 204
}

export type deleteCommentResponse401 = {
  data: void
  status: 401
}

export type deleteCommentResponse403 = {
  data: void
  status: 403
}

export type deleteCommentResponse404 = {
  data: void
  status: 404
}
    
export type deleteCommentResponseSuccess = (deleteCommentResponse204) & {
  headers: Headers;
};
export type deleteCommentResponseError = (deleteCommentResponse401 | deleteCommentResponse403 | deleteCommentResponse404) & {
  headers: Headers;
};

export type deleteCommentResponse = (deleteCommentResponseSuccess | deleteCommentResponseError)

export const getDeleteCommentUrl = (postId: number,
    commentId: number,) => {


  

  return `/api/v1/posts/${postId}/comments/${commentId}`
}

export const deleteComment = async (postId: number,
    commentId: number, options?: RequestInit): Promise<deleteCommentResponse> => {
  
  return customFetch<deleteCommentResponse>(getDeleteCommentUrl(postId,commentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteCommentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{postId: number;commentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{postId: number;commentId: number}, TContext> => {

const mutationKey = ['deleteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteComment>>, {postId: number;commentId: number}> = (props) => {
          const {postId,commentId} = props ?? {};

          return  deleteComment(postId,commentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteComment>>>
    
    export type DeleteCommentMutationError = void

    /**
 * @summary 댓글 삭제
 */
export const useDeleteComment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{postId: number;commentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteComment>>,
        TError,
        {postId: number;commentId: number},
        TContext
      > => {
      return useMutation(getDeleteCommentMutationOptions(options), queryClient);
    }
    