/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * IGRUS Web API
 * 인하대학교 정보통신처 소속 컴퓨터 연구 동아리 IGRUS 웹사이트 API

## 인증 방식

이 API는 JWT (JSON Web Token) 기반 Bearer 인증을 사용합니다.

### 인증 헤더 형식
```
Authorization: Bearer {access_token}
```

### 사용 방법
1. 로그인 API를 호출하여 Access Token을 발급받습니다.
2. 인증이 필요한 API 호출 시, HTTP 헤더에 위 형식으로 토큰을 포함합니다.

### 예시
```
GET /api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

### 토큰 정보
- **Access Token**: API 요청 인증에 사용 (유효 기간: 설정에 따름)
- **Refresh Token**: Access Token 갱신에 사용 (유효 기간: 설정에 따름)

### 주의사항
- Access Token이 만료되면 Refresh Token을 사용하여 새로운 Access Token을 발급받아야 합니다.
- Refresh Token도 만료되면 다시 로그인해야 합니다.

 * OpenAPI spec version: ec724ff
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateMemberInquiryRequest,
  GetMyInquiriesParams,
  InquiryCreateResponse,
  InquiryListPageResponse,
  InquiryResponse,
} from ".././models";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 로그인한 회원이 문의를 작성합니다. JWT 인증이 필요합니다.
 * @summary 회원 문의 작성
 */
export type createMemberInquiryResponse201 = {
  data: InquiryCreateResponse;
  status: 201;
};

export type createMemberInquiryResponse400 = {
  data: void;
  status: 400;
};

export type createMemberInquiryResponse401 = {
  data: void;
  status: 401;
};

export type createMemberInquiryResponseSuccess =
  createMemberInquiryResponse201 & {
    headers: Headers;
  };
export type createMemberInquiryResponseError = (
  | createMemberInquiryResponse400
  | createMemberInquiryResponse401
) & {
  headers: Headers;
};

export type createMemberInquiryResponse =
  | createMemberInquiryResponseSuccess
  | createMemberInquiryResponseError;

export const getCreateMemberInquiryUrl = () => {
  return `/api/v1/inquiries/member`;
};

export const createMemberInquiry = async (
  createMemberInquiryRequest: CreateMemberInquiryRequest,
  options?: RequestInit,
): Promise<createMemberInquiryResponse> => {
  return customFetch<createMemberInquiryResponse>(getCreateMemberInquiryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMemberInquiryRequest),
  });
};

export const getCreateMemberInquiryMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMemberInquiry>>,
    TError,
    { data: CreateMemberInquiryRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMemberInquiry>>,
  TError,
  { data: CreateMemberInquiryRequest },
  TContext
> => {
  const mutationKey = ["createMemberInquiry"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMemberInquiry>>,
    { data: CreateMemberInquiryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createMemberInquiry(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMemberInquiryMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMemberInquiry>>
>;
export type CreateMemberInquiryMutationBody = CreateMemberInquiryRequest;
export type CreateMemberInquiryMutationError = void;

/**
 * @summary 회원 문의 작성
 */
export const useCreateMemberInquiry = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createMemberInquiry>>,
      TError,
      { data: CreateMemberInquiryRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createMemberInquiry>>,
  TError,
  { data: CreateMemberInquiryRequest },
  TContext
> => {
  return useMutation(
    getCreateMemberInquiryMutationOptions(options),
    queryClient,
  );
};
/**
 * 로그인한 회원의 문의 목록을 조회합니다. JWT 인증이 필요합니다.
 * @summary 내 문의 목록 조회
 */
export type getMyInquiriesResponse200 = {
  data: InquiryListPageResponse;
  status: 200;
};

export type getMyInquiriesResponse401 = {
  data: void;
  status: 401;
};

export type getMyInquiriesResponseSuccess = getMyInquiriesResponse200 & {
  headers: Headers;
};
export type getMyInquiriesResponseError = getMyInquiriesResponse401 & {
  headers: Headers;
};

export type getMyInquiriesResponse =
  | getMyInquiriesResponseSuccess
  | getMyInquiriesResponseError;

export const getGetMyInquiriesUrl = (params?: GetMyInquiriesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/inquiries/my?${stringifiedParams}`
    : `/api/v1/inquiries/my`;
};

export const getMyInquiries = async (
  params?: GetMyInquiriesParams,
  options?: RequestInit,
): Promise<getMyInquiriesResponse> => {
  return customFetch<getMyInquiriesResponse>(getGetMyInquiriesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMyInquiriesQueryKey = (params?: GetMyInquiriesParams) => {
  return [`/api/v1/inquiries/my`, ...(params ? [params] : [])] as const;
};

export const getGetMyInquiriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyInquiries>>,
  TError = void,
>(
  params?: GetMyInquiriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiries>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyInquiriesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInquiries>>> = ({
    signal,
  }) => getMyInquiries(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyInquiries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyInquiriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyInquiries>>
>;
export type GetMyInquiriesQueryError = void;

export function useGetMyInquiries<
  TData = Awaited<ReturnType<typeof getMyInquiries>>,
  TError = void,
>(
  params: undefined | GetMyInquiriesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiries>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInquiries>>,
          TError,
          Awaited<ReturnType<typeof getMyInquiries>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyInquiries<
  TData = Awaited<ReturnType<typeof getMyInquiries>>,
  TError = void,
>(
  params?: GetMyInquiriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiries>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInquiries>>,
          TError,
          Awaited<ReturnType<typeof getMyInquiries>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyInquiries<
  TData = Awaited<ReturnType<typeof getMyInquiries>>,
  TError = void,
>(
  params?: GetMyInquiriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiries>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 문의 목록 조회
 */

export function useGetMyInquiries<
  TData = Awaited<ReturnType<typeof getMyInquiries>>,
  TError = void,
>(
  params?: GetMyInquiriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiries>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyInquiriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 로그인한 회원의 특정 문의 상세 정보를 조회합니다. JWT 인증이 필요합니다.
 * @summary 내 문의 상세 조회
 */
export type getMyInquiryResponse200 = {
  data: InquiryResponse;
  status: 200;
};

export type getMyInquiryResponse401 = {
  data: void;
  status: 401;
};

export type getMyInquiryResponse404 = {
  data: void;
  status: 404;
};

export type getMyInquiryResponseSuccess = getMyInquiryResponse200 & {
  headers: Headers;
};
export type getMyInquiryResponseError = (
  | getMyInquiryResponse401
  | getMyInquiryResponse404
) & {
  headers: Headers;
};

export type getMyInquiryResponse =
  | getMyInquiryResponseSuccess
  | getMyInquiryResponseError;

export const getGetMyInquiryUrl = (id: number) => {
  return `/api/v1/inquiries/my/${id}`;
};

export const getMyInquiry = async (
  id: number,
  options?: RequestInit,
): Promise<getMyInquiryResponse> => {
  return customFetch<getMyInquiryResponse>(getGetMyInquiryUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetMyInquiryQueryKey = (id: number) => {
  return [`/api/v1/inquiries/my/${id}`] as const;
};

export const getGetMyInquiryQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyInquiry>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiry>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyInquiryQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInquiry>>> = ({
    signal,
  }) => getMyInquiry(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyInquiry>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyInquiryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyInquiry>>
>;
export type GetMyInquiryQueryError = void;

export function useGetMyInquiry<
  TData = Awaited<ReturnType<typeof getMyInquiry>>,
  TError = void,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiry>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInquiry>>,
          TError,
          Awaited<ReturnType<typeof getMyInquiry>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyInquiry<
  TData = Awaited<ReturnType<typeof getMyInquiry>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiry>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInquiry>>,
          TError,
          Awaited<ReturnType<typeof getMyInquiry>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyInquiry<
  TData = Awaited<ReturnType<typeof getMyInquiry>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiry>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 문의 상세 조회
 */

export function useGetMyInquiry<
  TData = Awaited<ReturnType<typeof getMyInquiry>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyInquiry>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyInquiryQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
